---

name: $(Build.SourceBranchName)-$(Date:yyyyMMdd)_$(Rev:r)
trigger: none
pr: none

resources:
  repositories:
    - repository: dtos-devops-templates
      type: github
      name: NHSDigital/dtos-devops-templates
      ref: d6d6e3e99459d9d71a83fa5affa900a6c339a3b5
      endpoint: NHSDigital

variables:
  - group: DEV_hub_backend_remote_state

stages:
- stage: db_changes_stage
  displayName: Database changes
  jobs:
  - job: db_changes
    pool:
      name: private-pool-dev-uks
    displayName: Apply database changes
    variables:
      - group: INT_core_backend
      - group: INT_image_pipelines
    steps:
      - checkout: self
      - checkout: dtos-devops-templates
      - template: .azuredevops/templates/steps/app-container-job-start.yaml@dtos-devops-templates
        parameters:
          serviceConnection: $(SERVICE_CONNECTION)
          targetSubscriptionId: $(TF_VAR_TARGET_SUBSCRIPTION_ID)
          resourceGroupName: $(RESOURCE_GROUP_NAME_SQL)
          jobName: $(DATABASE_MANAGEMENT_JOB_NAME)

- stage: re_tag_stage
  displayName: ACR re-tag
  jobs:
  - job: re_tag
    pool:
      name: private-pool-dev-uks
    displayName: Update/copy Docker images with new tag
    variables:
      - group: INT_image_pipelines
    steps:
      - template: .azuredevops/templates/steps/acr-import-retag.yaml@dtos-devops-templates
        parameters:
          serviceConnection: $(SERVICE_CONNECTION)

- stage: deploy_image_stage
  displayName: Deploy images
  jobs:
  - job: deploy_images
    pool:
      name: private-pool-dev-uks
    displayName: Deploy Docker images to function apps
    variables:
      - group: INT_core_backend
      - group: INT_image_pipelines
    steps:
      - template: .azuredevops/templates/steps/deploy-images-from-acr.yaml@dtos-devops-templates
        parameters:
          serviceConnection: $(SERVICE_CONNECTION)

- stage: smoke_e2e_tests
  displayName: Run Smoke E2E Tests
  variables:
  - group: INT_automation_testing_pipeline
  jobs:
    - job: smoke_e2e_tests
      pool:
        name: private-pool-dev-uks

      steps:
      - template: .azuredevops/templates/steps/run-post-deployment-pw-tests.yaml@dtos-devops-templates
        parameters:
          serviceConnection: $(SERVICE_CONNECTION)
          testProjectDirectory: 'tests/playwright-tests'
          testfileDirectory: 'src/tests/e2e/testFiles'
          testProjectName: 'tests'
          testType: 'smoke_e2e'

- stage: regression_api_tests
  displayName: Run Regression API Tests
  dependsOn: smoke_e2e_tests
  condition: succeededOrFailed()
  variables:
  - group: INT_automation_testing_pipeline
  jobs:
    - job: regression_api_tests
      pool:
        name: private-pool-dev-uks

      steps:
      - template: .azuredevops/templates/steps/run-post-deployment-pw-tests.yaml@dtos-devops-templates
        parameters:
          serviceConnection: $(SERVICE_CONNECTION)
          testProjectDirectory: 'tests/playwright-tests'
          testfileDirectory: 'src/tests/e2e/testFiles'
          testProjectName: 'tests'
          testType: 'regression_api'

- stage: regression_e2e_epic1_tests
  displayName: Run Regression E2E Epic1 Tests
  dependsOn: regression_api_tests
  condition: succeededOrFailed()
  variables:
  - group: INT_automation_testing_pipeline
  jobs:
    - job: regression_e2e_epic1_tests
      pool:
        name: private-pool-dev-uks

      steps:
      - template: .azuredevops/templates/steps/run-post-deployment-pw-tests.yaml@dtos-devops-templates
        parameters:
          serviceConnection: $(SERVICE_CONNECTION)
          testProjectDirectory: 'tests/playwright-tests'
          testfileDirectory: 'src/tests/e2e/testFiles'
          testProjectName: 'tests'
          testType: 'regression_e2e_epic1'

- stage: regression_e2e_epic2_tests
  displayName: Run Regression E2E Epic2 Tests
  dependsOn: regression_e2e_epic1_tests
  condition: succeededOrFailed()
  variables:
  - group: INT_automation_testing_pipeline
  jobs:
    - job: regression_e2e_epic2_tests
      pool:
        name: private-pool-dev-uks

      steps:
      - template: .azuredevops/templates/steps/run-post-deployment-pw-tests.yaml@dtos-devops-templates
        parameters:
          serviceConnection: $(SERVICE_CONNECTION)
          testProjectDirectory: 'tests/playwright-tests'
          testfileDirectory: 'src/tests/e2e/testFiles'
          testProjectName: 'tests'
          testType: 'regression_e2e_epic2'

- stage: regression_e2e_epic3_tests
  displayName: Run Regression E2E Epic3 Tests
  dependsOn: regression_e2e_epic2_tests
  condition: succeededOrFailed()
  variables:
  - group: INT_automation_testing_pipeline
  jobs:
    - job: regression_e2e_epic3_tests
      pool:
        name: private-pool-dev-uks

      steps:
      - template: .azuredevops/templates/steps/run-post-deployment-pw-tests.yaml@dtos-devops-templates
        parameters:
          serviceConnection: $(SERVICE_CONNECTION)
          testProjectDirectory: 'tests/playwright-tests'
          testfileDirectory: 'src/tests/e2e/testFiles'
          testProjectName: 'tests'
          testType: 'regression_e2e_epic3'
