---

name: $(Build.SourceBranchName)-$(Date:yyyyMMdd)_$(Rev:r)
trigger: none
pr: none

resources:
  repositories:
    - repository: dtos-devops-templates
      type: github
      name: NHSDigital/dtos-devops-templates
      ref: 408fa638a2c05f94bf2aaab7c00d702dad1d00ca
      endpoint: NHSDigital

variables:
  - group: DEV_hub_backend_remote_state

stages:
- stage: db_changes_stage
  displayName: Database changes
  jobs:
  - job: db_changes
    pool:
      name: private-pool-dev-uks
    displayName: Apply database changes
    variables:
      - group: DEV_core_backend
      - group: DEV_image_pipelines
    steps:
      - checkout: self
      - checkout: dtos-devops-templates
      - template: .azuredevops/templates/steps/apply-database-changes.yaml@dtos-devops-templates
        parameters:
          serviceConnection: $(SERVICE_CONNECTION)

- stage: deploy_image_stage
  displayName: Deploy images
  jobs:
  - job: deploy_images
    pool:
      name: private-pool-dev-uks
    displayName: Deploy Docker images to function apps
    variables:
      - group: DEV_core_backend
      - group: DEV_image_pipelines
    steps:
      - template: .azuredevops/templates/steps/deploy-images-from-acr.yaml@dtos-devops-templates
        parameters:
          serviceConnection: $(SERVICE_CONNECTION)

- stage: post_deployment_tests_stage
  displayName: Post-deployment tests
  variables:
  - group: DEV_automation_testing_pipeline
  jobs:
  - job: post_deployment_tests
    displayName: Run post-deployment tests
    pool:
      name: private-pool-dev-uks
    variables:
      AppSettings.ConnectionStrings.DtOsDatabaseConnectionString: $(DTOS_DATABASE_CONNECTION_STRING)
      AppSettings.CloudFileStorageConnectionString: $(CAASFOLDER_STORAGE_CONNECTION_STRING)
      AppSettings.ManagedIdentityClientId: $(MANAGED_IDENTITY_CLIENT_ID)
      AppSettings.IsCloudEnvironment: $(Is_CloudEnvironment)
    steps:
    - template: .azuredevops/templates/steps/run-post-deployment-tests.yaml@dtos-devops-templates
      parameters:
        serviceConnection: $(SERVICE_CONNECTION)
        testProjectDirectory: 'tests/smoke-tests/NHS.CohortManager.SmokeTests'
        testProjectName: 'NHS.CohortManager.SmokeTests'
