---

name: $(Build.SourceBranchName)-$(Date:yyyyMMdd)_$(Rev:r)
trigger: none
pr: none

resources:
  repositories:
    - repository: dtos-devops-templates
      type: github
      name: NHSDigital/dtos-devops-templates
      ref: ac0aaf63e6d27820912918e2ecd23feec518ce51
      endpoint: NHSDigital

variables:
  - group: DEV_hub_backend_remote_state

stages:
- stage: db_changes_stage
  displayName: Database changes
  jobs:
  - job: db_changes
    pool:
      name: private-pool-dev-uks
    displayName: Apply database changes
    variables:
      - group: NFT_core_backend
      - group: NFT_image_pipelines
    steps:
      - checkout: self
      - checkout: dtos-devops-templates
      - template: .azuredevops/templates/steps/apply-database-changes.yaml@dtos-devops-templates
        parameters:
          serviceConnection: $(SERVICE_CONNECTION)

- stage: re_tag_stage
  displayName: ACR re-tag
  jobs:
  - job: re_tag
    pool:
      name: private-pool-prod-uks
    displayName: Update/copy Docker images with new tag
    variables:
      - group: NFT_image_pipelines
    steps:
      - template: .azuredevops/templates/steps/acr-import-retag.yaml@dtos-devops-templates
        parameters:
          serviceConnection: $(SERVICE_CONNECTION)

- stage: deploy_image_stage
  displayName: Deploy images
  jobs:
  - job: deploy_images
    pool:
      name: private-pool-dev-uks
    displayName: Deploy Docker images to function apps
    variables:
      - group: NFT_core_backend
      - group: NFT_image_pipelines
    steps:
      - template: .azuredevops/templates/steps/deploy-images-from-acr.yaml@dtos-devops-templates
        parameters:
          serviceConnection: $(SERVICE_CONNECTION)

- stage: post_deployment_tests_stage
  displayName: Post-deployment tests
  variables:
  - group: NFT_automation_testing_pipeline
  jobs:
  - job: post_deployment_tests
    displayName: Run post-deployment tests
    pool:
      name: private-pool-dev-uks

    steps:
    - template: .azuredevops/templates/steps/run-post-deployment-pw-tests.yaml@dtos-devops-templates
      parameters:
        serviceConnection: $(SERVICE_CONNECTION)
        testProjectDirectory: 'tests/playwright-tests'
        testfileDirectory: 'src/tests/e2e/testFiles'
        testProjectName: 'tests'

