---

name: $(Build.SourceBranchName)-$(Date:yyyyMMdd)_$(Rev:r)
trigger: none
pr: none

pool:
  #vmImage: ubuntu-latest
  name: private-pool-prod-uks

resources:
  repositories:
    - repository: dtos-devops-templates
      type: github
      name: NHSDigital/dtos-devops-templates
      ref: 7d1540f568fb00f527e388aa0acfff807c6d367c
      endpoint: NHSDigital

parameters:
  - name: dockerImageTag
    displayName: 'Docker Image Tag'
    type: string
    default: production

variables:
  - group: PROD_core_backend
  - group: PROD_audit_backend_remote_state
  - group: PRD_hub_backend_remote_state
  - name: TF_VERSION
    value: 1.11.4
  - name: TF_PLAN_ARTIFACT
    value: tf_plan_core_PROD
  - name: TF_DIRECTORY
    value: $(System.DefaultWorkingDirectory)/$(System.TeamProject)/infrastructure/tf-core
  - name: ENVIRONMENT
    value: production

stages:
  - stage: terraform_plan
    displayName: Terraform Plan
    condition: eq(variables['Build.Reason'], 'Manual')
    variables:
      tfVarsFile: environments/$(ENVIRONMENT).tfvars
    jobs:
      - job: init_and_plan
        displayName: Init, plan, store artifact
        steps:
          - checkout: self
          - checkout: dtos-devops-templates
          - template: .azuredevops/templates/steps/tf_plan.yaml@dtos-devops-templates
            parameters:
              tfCommandOptions: '-var="docker_image_tag=${{ parameters.dockerImageTag }}"'

  - stage: terraform_apply
    displayName: Terraform Apply
    dependsOn: [terraform_plan]
    condition: and(eq(dependencies.terraform_plan.outputs['init_and_plan.TerraformPlan.changesPresent'], 'true'), eq(variables['Build.Reason'], 'Manual'))
    jobs:
      - deployment: terraform_apply
        displayName: Init, get plan artifact, apply
        environment: $(ENVIRONMENT)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - checkout: dtos-devops-templates
                - template: .azuredevops/templates/steps/tf_apply.yaml@dtos-devops-templates
