---

name: $(Build.SourceBranchName)-$(Date:yyyyMMdd)_$(Rev:r)
trigger: none
pr: none

resources:
  repositories:
    - repository: dtos-devops-templates
      type: github
      name: NHSDigital/dtos-devops-templates
      ref: e4e68ea29c4fab7014caf900063fe70f785732f3
      endpoint: NHSDigital

parameters:
  - name: dockerImageTag
    displayName: 'Docker Image Tag'
    type: string
    default: development
  - name: pipelineAction
    displayName: 'Pipeline Action'
    type: string
    values:
      - 'PlanOnly'
      - 'PlanApply'
    default: 'PlanApply'

stages:
  - stage: terraform_plan_SBX
    pool:
      name: private-pool-dev-uks
    displayName: Terraform Plan (SBX)
    condition: eq(variables['Build.Reason'], 'Manual')
    variables:
      - group: SBX_core_backend
      - group: SBX_audit_backend_remote_state
      - group: DEV_hub_backend_remote_state
      - name: TF_VERSION
        value: 1.11.4
      - name: TF_PLAN_ARTIFACT
        value: tf_plan_core_SANDBOX
      - name: TF_DIRECTORY
        value: $(System.DefaultWorkingDirectory)/$(System.TeamProject)/infrastructure/tf-core
      - name: ENVIRONMENT
        value: sandbox
      - name: tfVarsFile
        value: environments/$(ENVIRONMENT).tfvars
    jobs:
      - job: init_and_plan_SBX
        displayName: Init, plan, store artifact (SBX)
        condition: in('${{ parameters.pipelineAction }}', 'PlanApply', 'PlanOnly')
        steps:
          - checkout: self
          - checkout: dtos-devops-templates
          - template: .azuredevops/templates/steps/tf_plan.yaml@dtos-devops-templates
            parameters:
              tfCommandOptions: '-var="docker_image_tag=${{ parameters.pipelineAction }}"'
      
      # Test job to apply the plan
      - job: terraform_apply
        displayName: Apply Terraform Plan (SBX)
        dependsOn: init_and_plan_SBX
        condition: and(eq(dependencies.terraform_plan_SBX.outputs['init_and_plan_SBX.TerraformPlan.changesPresent'], 'true'), eq('${{ parameters.pipelineAction }}', 'PlanApply'), eq(variables['Build.Reason'], 'Manual'))
        steps:
          - task: AzureCLI@2
            displayName: Apply Plan
            inputs:
              azureSubscription: $(SERVICE_CONNECTION)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Applying TF Plan..."

      # - deployment: terraform_apply
      #   displayName: Init, get plan artifact, apply
      #   dependsOn: [init_and_plan_SBX]
      #   condition: and(eq(dependencies.terraform_plan_SBX.outputs['init_and_plan_SBX.TerraformPlan.changesPresent'], 'true'), eq('${{ parameters.pipelineAction }}', 'Apply'), eq(variables['Build.Reason'], 'Manual'))
      #   environment: $(ENVIRONMENT)
      #   strategy:
      #     runOnce:
      #       deploy:
      #         steps:
      #           - checkout: self
      #           - checkout: dtos-devops-templates
      #           - template: .azuredevops/templates/steps/tf_apply.yaml@dtos-devops-templates

      - job: db_changes_SBX
        displayName: Apply database changes (SBX)
        dependsOn: init_and_plan_SBX
        variables:
          - group: SBX_core_backend
          - group: SBX_image_pipelines
        steps:
          - checkout: self
          - checkout: dtos-devops-templates
          - task: AzureCLI@2
            displayName: Apply database changes
            inputs:
              azureSubscription: $(SERVICE_CONNECTION)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Applying database changes..."

          # Comment out for testing
          # - template: .azuredevops/templates/steps/app-container-job-start.yaml@dtos-devops-templates
          #   parameters:
          #     serviceConnection: $(SERVICE_CONNECTION)
          #     targetSubscriptionId: $(TF_VAR_TARGET_SUBSCRIPTION_ID)
          #     resourceGroupName: $(RESOURCE_GROUP_NAME_SQL)
          #     jobName: $(DATABASE_MANAGEMENT_JOB_NAME)
