---

trigger: none

pr: none

variables:
  - group: global_variable_group
  - name: acr_dev_name
    value: acrukscohmandev
  - name: acr_dev_rg
    value: rg-cohort-manager-dev-uks

parameters:
  - name: containers
    type: object
    default:
      - name: devops-testing-service
        repository: cohort-manager-devops-testing-service
        tag:
          - development
      - name: receive-caas-file
        repository: cohort-manager-receive-caas-file
        tag:
          - development
      - name: process-caas-file
        repository: cohort-manager-process-caas-file
        tag:
          - development
      - name: add-participant
        repository: cohort-manager-add-participant
        tag:
          - development
      - name: remove-participant
        repository: cohort-manager-remove-participant
        tag:
          - development
      - name: update-participant
        repository: cohort-manager-update-participant
        tag:
          - development
      - name: create-participant
        repository: cohort-manager-create-participant
        tag:
          - development
      - name: mark-participant-as-eligible
        repository: cohort-manager-mark-participant-as-eligible
        tag:
          - development
      - name: mark-participant-as-ineligible
        repository: cohort-manager-mark-participant-as-ineligible
        tag:
          - development
      - name: update-participant-details
        repository: cohort-manager-update-participant-details
        tag:
          - development
      - name: create-exception
        repository: cohort-manager-create-exception
        tag:
          - development
      - name: get-validation-exceptions
        repository: cohort-manager-get-validation-exceptions
        tag:
          - development
      - name: demographic-data-service
        repository: cohort-manager-demographic-data-service
        tag:
          - development
      - name: file-validation
        repository: cohort-manager-file-validation
        tag:
          - development
      - name: static-validation
        repository: cohort-manager-static-validation
        tag:
          - development
      - name: lookup-validation
        repository: cohort-manager-lookup-validation
        tag:
          - development
      - name: demographic-data-management
        repository: cohort-manager-demographic-data-management
        tag:
          - development
      - name: add-cohort-distribution-data
        repository: cohort-manager-add-cohort-distribution-data
        tag:
          - development
      - name: retrieve-cohort-distribution-data
        repository: cohort-manager-retrieve-cohort-distribution-data
        tag:
          - development
      - name: retrieve-cohort-replay
        repository: cohort-manager-retrieve-cohort-replay
        tag:
          - development
      - name: retrieve-cohort-request-audit
        repository: cohort-manager-retrieve-cohort-request-audit
        tag:
          - development
      - name: remove-cohort-distribution-data
        repository: cohort-manager-remove-cohort-distribution-data
        tag:
          - development
      - name: transform-data-service
        repository: cohort-manager-transform-data-service
        tag:
          - development
      - name: allocate-service-provider
        repository: cohort-manager-allocate-service-provider
        tag:
          - development
      - name: create-cohort-distribution
        repository: cohort-manager-create-cohort-distribution
        tag:
          - development
      - name: retrieve-participant-data
        repository: cohort-manager-retrieve-participant-data
        tag:
          - development
      - name: validate-cohort-distribution-record
        repository: cohort-manager-validate-cohort-distribution-record
        tag:
          - development
      - name: remove-validation-exception-data
        repository: cohort-manager-remove-validation-exception-data
        tag:
          - development
      - name: retrieve-mesh-file
        repository: cohort-manager-retrieve-mesh-file
        tag:
          - development


resources:
  containers:
    - ${{ each container in parameters.containers }}:
        - container: ${{ container.name }}
          type: ACR
          azureSubscription: sc-cohort-manager-dev
          resourceGroup: rg-cohort-manager-dev-uks
          registry: acrukscohmandev.azurecr.io
          repository: ${{ container.repository }}
          trigger:
            enabled: true  # Ensure triggers are enabled
            tags:
              include:
                - ${{ container.tag }}

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: GetTriggeringAlias
    displayName: Get triggering alias
    steps:
    - checkout: none
    - task: AzureCLI@2
      name: GetTriggeringAlias
      displayName: Get triggering alias
      inputs:
        azureSubscription: sc-cohort-manager-dev
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Image name: $RESOURCES_TRIGGERINGALIAS"
          functionAppName="$(echo $RESOURCES_TRIGGERINGALIAS)"
          echo $functionAppName
          echo "##vso[task.setvariable variable=functionAppName;isoutput=true]$functionAppName"

  - job: SendSlackAlert
    displayName: Send Slack alert
    dependsOn: GetTriggeringAlias
    variables:
      functionAppName: $[ dependencies.GetTriggeringAlias.outputs['GetTriggeringAlias.functionAppName'] ]
    steps:
    - checkout: self
    - task: AzureCLI@2
      name: SendSlackAlert
      displayName: Send Slack Alert
      inputs:
        azureSubscription: sc-cohort-manager-dev
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "the function name is: $(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
          pip install python-hcl2
          set -x
          chmod 755 scripts/azure/GetImageTagsByManifest.sh
          list_image_tags=$(scripts/azure/GetImageTagsByManifest.sh -g $(acr_dev_rg) -s $(ACR_DEV_SUBSCRIPTION_ID) -c $(acr_dev_name) -f $(functionAppName) )
          echo new list: "${list_image_tags}"
          export SLACK_WEBHOOK_URL=$(SLACK_WEBHOOK_URL)
          python3 scripts/azure/SlackWebhookController.py -v -f $(functionAppName) -c "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)" -t "${list_image_tags}"

  - job: waitForValidation
    displayName: Wait for external validation
    dependsOn: GetTriggeringAlias
    variables:
      functionAppName: $[ dependencies.GetTriggeringAlias.outputs['GetTriggeringAlias.functionAppName'] ]
    pool: server
    timeoutInMinutes: 1440 # task times out in 1 day
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # task times out in 1 day
        inputs:
          notifyUsers: |
            richard.kingston2@nhs.net
            alastair.lock1@nhs.net
          instructions: "Please validate the build configuration for: $(functionAppName)"
          onTimeout: "resume"

  - job: UpdateFunctionApp
    displayName: Update Function App
    dependsOn:
      - waitForValidation
      - GetTriggeringAlias
    variables:
      functionAppName: $[ dependencies.GetTriggeringAlias.outputs['GetTriggeringAlias.functionAppName'] ]
    steps:
    - task: AzureCLI@2
      name: UpdateFunctionApp
      displayName: Update Function App
      inputs:
        azureSubscription: sc-cohort-manager-dev
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Restarting Function App: $(functionAppName)"
          az functionapp restart --name $(functionAppName) --resource-group $(acr_dev_rg)

          pip install python-hcl2
          export SLACK_WEBHOOK_URL=$(SLACK_WEBHOOK_URL)
          chmod 755 scripts/azure/GetImageTagsByManifest.sh
          list_image_tags=$(scripts/azure/GetImageTagsByManifest.sh -g $(acr_dev_rg) -s $(ACR_DEV_SUBSCRIPTION_ID) -c $(acr_dev_name) -f $(functionAppName) )
          python3 scripts/azure/SlackWebhookController.py -v -f $(functionAppName) -t "${list_image_tags}"
