---

name: $(Build.SourceBranchName)-$(Date:yyyyMMdd)_$(Rev:r)
trigger: none
pr: none

variables:
  - name: hostPoolName
    value: private-pool-dev-uks
  - group: SBRK_core_backend

stages:

- template: ../templates/owasp-zap-report-core-common.yaml
  parameters:
    serviceConnection: $(SERVICE_CONNECTION)
    subscriptionId: $(TF_VAR_TARGET_SUBSCRIPTION_ID)
    resourceGroup: $(FUNCTION_RESOURCE_GROUP)
