---

name: $(Build.SourceBranchName)-$(Date:yyyyMMdd)_$(Rev:r)
trigger: none
pr: none

resources:
  repositories:
  - repository: dtos-devops-templates
    type: github
    name: NHSDigital/dtos-devops-templates
    ref: 7dd6e83de82475570a27e172b95be8d30f488695
    endpoint: NHSDigital

parameters:
- name: destEnvironmentShortName
  displayName: Destination Environment Short Name
  type: string
  values:
  - dev
  default: dev

variables:
- group: DEV_automation_testing_pipeline
variables:
  - group: DEV_automation_testing_pipeline
  - name: TARGET_ENVIRONMENT
    value: ${{ parameters.destEnvironmentShortName }}
  - name: ConnectionStrings__DtOsDatabaseConnectionString
    value: $(DATABASE_CONNECTION_STRING)
  - name: AzureWebJobsStorage
    value: $(STORAGE_CONNECTION_STRING)
stages:
- stage: post_deployment_tests_stage
  displayName: Post-deployment tests

  jobs:
  - job: post_deployment_tests
    pool:
      name: private-pool-prod-uks
    displayName: Run post-deployment tests

    steps:
    - checkout: self
    - template: ../templates/steps/run-post-deployment-tests.yaml
      parameters:
        serviceConnection: sc-cohort-manager-dev
