---
name: $(Build.SourceBranchName)-$(Date:yyyyMMdd)_$(Rev:r)
trigger: none
pr: none

schedules:
  - cron: "15 7 * * 1-5" # Every weekday (Mon-Fri) at 07:15 UTC i.e 8:15 BST
    displayName: Weekdays run
    branches:
      include:
        - main # Change to your default branch if needed
    always: true

resources:
  repositories:
    - repository: dtos-devops-templates
      type: github
      name: NHSDigital/dtos-devops-templates
      ref: c5b352eaad08403f0addac347b07ede4fa643556
      endpoint: NHSDigital

variables:
  - group: DEV_automation_testing_pipeline

parameters:
  - name: destEnvironmentShortName
    displayName: Destination Environment Short Name
    type: string
    values:
      - dev
    default: dev

  - name: testTypes
    type: object
    default:
      - smoke_e2e
      - regression_api
      - regression_e2e_epic1
      - regression_e2e_epic2
      - regression_e2e_epic3

stages:
  ${{ each testType in parameters.testTypes }}:
    - stage: ${{ testType }}_stage
      displayName: Run ${{ testType }} Tests
      ${{ if ne(testTypeIndex, 0) }}:
        dependsOn: ${{ format('{0}_stage', parameters.testTypes[testTypeIndex - 1]) }}
        condition: succeededOrFailed()
      variables:
        TARGET_ENVIRONMENT: ${{ parameters.destEnvironmentShortName }}
      jobs:
        - job: ${{ testType }}_job
          pool:
            name: private-pool-dev-uks
          steps:
            - template: .azuredevops/templates/steps/run-post-deployment-pw-tests.yaml@dtos-devops-templates
              parameters:
                serviceConnection: sc-cohort-manager-dev
                testProjectDirectory: "tests/playwright-tests"
                testfileDirectory: "src/tests/e2e/testFiles"
                testProjectName: "tests"
                testType: ${{ testType }}
