---

name: $(Build.SourceBranchName)-$(Date:yyyyMMdd)_$(Rev:r)
trigger: none
pr: none

resources:
  repositories:
  - repository: dtos-devops-templates
    type: github
    name: NHSDigital/dtos-devops-templates
    ref: f11707c8a8884950794856fd7fa379fa88f98d3a
    endpoint: NHSDigital

variables:
- group: DEV_automation_testing_pipeline

parameters:
- name: destEnvironmentShortName
  displayName: Destination Environment Short Name
  type: string
  values:
  - dev
  default: dev

stages:
- stage: post_deployment_tests_stage
  displayName: Post-deployment tests

  variables:
  - name: TARGET_ENVIRONMENT
    value: ${{ parameters.destEnvironmentShortName }}

  jobs:
  - job: post_deployment_tests_smoke
    displayName: Run post-deployment smoke tests
    pool:
      name: private-pool-dev-uks
    variables:
      AppSettings.ConnectionStrings.DtOsDatabaseConnectionString: $(DTOS_DATABASE_CONNECTION_STRING)
      AppSettings.CloudFileStorageConnectionString: $(CAASFOLDER_STORAGE_CONNECTION_STRING)
      AppSettings.ManagedIdentityClientId: $(MANAGED_IDENTITY_CLIENT_ID)
      AppSettings.IsCloudEnvironment: $(Is_CloudEnvironment)
    steps:
    - template: .azuredevops/templates/steps/run-post-deployment-pw-tests.yaml@dtos-devops-templates
      parameters:
        serviceConnection: sc-cohort-manager-dev
        testProjectDirectory: 'tests/playwright-tests'
        testProjectName: 'tests'
