---
name: $(Build.SourceBranchName)-$(Date:yyyyMMdd)_$(Rev:r)
trigger: none
pr: none

resources:
  repositories:
  - repository: dtos-devops-templates
    type: github
    name: NHSDigital/dtos-devops-templates
    ref: 1c899d5e79c0a8fb646ad31574e89535c2064a14
    endpoint: NHSDigital

variables:
- group: DEV_automation_testing_pipeline

parameters:
- name: destEnvironmentShortName
  displayName: Destination Environment Short Name
  type: string
  values:
  - dev
  default: dev

stages:
- stage: post_deployment_tests_stage
  displayName: Post-deployment tests

  variables:
  - name: TARGET_ENVIRONMENT
    value: ${{ parameters.destEnvironmentShortName }}

  jobs:
  - job: post_deployment_tests
    displayName: Run post-deployment tests
    pool:
      name: private-pool-dev-uks

    steps:
      - template: .azuredevops/templates/steps/run-post-deployment-pw-tests.yaml@dtos-devops-templates
        parameters:
          serviceConnection: sc-cohort-manager-dev
          testProjectDirectory: 'tests/playwright-tests'
          testfileDirectory: 'src/tests/e2e/testFiles'
          testProjectName: 'tests'
          testType: 'smoke:e2e'

      - template: .azuredevops/templates/steps/run-post-deployment-pw-tests.yaml@dtos-devops-templates
        parameters:
          serviceConnection: sc-cohort-manager-dev
          testProjectDirectory: 'tests/playwright-tests'
          testfileDirectory: 'src/tests/e2e/testFiles'
          testProjectName: 'tests'
          testType: 'test:regression:api'

      - template: .azuredevops/templates/steps/run-post-deployment-pw-tests.yaml@dtos-devops-templates
        parameters:
          serviceConnection: sc-cohort-manager-dev
          testProjectDirectory: 'tests/playwright-tests'
          testfileDirectory: 'src/tests/e2e/testFiles'
          testProjectName: 'tests'
          testType: 'test:regression:e2e:epic1'

      - template: .azuredevops/templates/steps/run-post-deployment-pw-tests.yaml@dtos-devops-templates
        parameters:
          serviceConnection: sc-cohort-manager-dev
          testProjectDirectory: 'tests/playwright-tests'
          testfileDirectory: 'src/tests/e2e/testFiles'
          testProjectName: 'tests'
          testType: 'test:regression:e2e:epic2'

      - template: .azuredevops/templates/steps/run-post-deployment-pw-tests.yaml@dtos-devops-templates
        parameters:
          serviceConnection: sc-cohort-manager-dev
          testProjectDirectory: 'tests/playwright-tests'
          testfileDirectory: 'src/tests/e2e/testFiles'
          testProjectName: 'tests'
          testType: 'test:regression:e2e:epic3'
