---

name: $(Build.SourceBranchName)-$(Date:yyyyMMdd)_$(Rev:r)
trigger: none
pr: none

resources:
  repositories:
  - repository: dtos-devops-templates
    type: github
    name: NHSDigital/dtos-devops-templates
    ref: 0a1ae809e2b5f41a1974c5490595e08f591fb8c7
    endpoint: NHSDigital

variables:
- group: DEV_automation_testing_pipeline

parameters:
- name: destEnvironmentShortName
  displayName: Destination Environment Short Name
  type: string
  values:
  - dev
  default: dev

stages:
- stage: post_deployment_tests_stage
  displayName: Post-deployment tests

  variables:
  - name: TARGET_ENVIRONMENT
    value: ${{ parameters.destEnvironmentShortName }}

  jobs:
  - job: post_deployment_tests
    displayName: Run post-deployment tests
    pool:
      name: private-pool-dev-uks
    variables:
      AppSettings.ConnectionStrings.DtOsDatabaseConnectionString: $(DTOS_DATABASE_CONNECTION_STRING)
      AppSettings.caasFileStorage: $(CAASFOLDER_STORAGE_CONNECTION_STRING)
      AppSettings.ManagedIdentityClientId: $(MANAGED_IDENTITY_CLIENT_ID)

    steps:
    - template: .azuredevops/templates/steps/run-post-deployment-tests.yaml@dtos-devops-templates
      parameters:
        serviceConnection: sc-cohort-manager-dev
