---
name: $(Build.SourceBranchName)-$(Date:yyyyMMdd)_$(Rev:r)
trigger: none
pr: none

resources:
  repositories:
  - repository: dtos-devops-templates
    type: github
    name: NHSDigital/dtos-devops-templates
    ref: 1c899d5e79c0a8fb646ad31574e89535c2064a14
    endpoint: NHSDigital

variables:
- group: DEV_automation_testing_pipeline

parameters:
- name: destEnvironmentShortName
  displayName: Destination Environment Short Name
  type: string
  values:
  - dev
  default: dev

stages:
- stage: post_deployment_tests_stage
  displayName: Post-deployment tests

  variables:
  - name: TARGET_ENVIRONMENT
    value: ${{ parameters.destEnvironmentShortName }}

  jobs:
    # Smoke E2E Tests Job
    - job: smoke_e2e_tests
      displayName: Run Smoke E2E Tests
      pool:
        name: private-pool-dev-uks
      steps:
        - template: .azuredevops/templates/steps/run-post-deployment-pw-tests.yaml@dtos-devops-templates
          parameters:
            serviceConnection: sc-cohort-manager-dev
            testProjectDirectory: 'tests/playwright-tests'
            testfileDirectory: 'src/tests/e2e/testFiles'
            testProjectName: 'tests'
            testType: 'smoke:e2e'

    # Regression API Tests Job
    - job: regression_api_tests
      displayName: Run Regression API Tests
      pool:
        name: private-pool-dev-uks
      steps:
        - template: .azuredevops/templates/steps/run-post-deployment-pw-tests.yaml@dtos-devops-templates
          parameters:
            serviceConnection: sc-cohort-manager-dev
            testProjectDirectory: 'tests/playwright-tests'
            testfileDirectory: 'src/tests/e2e/testFiles'
            testProjectName: 'tests'
            testType: 'regression:api'

    # Regression E2E Epic1 Tests Job
    - job: regression_e2e_epic1_tests
      displayName: Run Regression E2E Epic1 Tests
      pool:
        name: private-pool-dev-uks
      steps:
        - template: .azuredevops/templates/steps/run-post-deployment-pw-tests.yaml@dtos-devops-templates
          parameters:
            serviceConnection: sc-cohort-manager-dev
            testProjectDirectory: 'tests/playwright-tests'
            testfileDirectory: 'src/tests/e2e/testFiles'
            testProjectName: 'tests'
            testType: 'regression:e2e:epic1'

    # Regression E2E Epic2 Tests Job
    - job: regression_e2e_epic2_tests
      displayName: Run Regression E2E Epic2 Tests
      pool:
        name: private-pool-dev-uks
      steps:
        - template: .azuredevops/templates/steps/run-post-deployment-pw-tests.yaml@dtos-devops-templates
          parameters:
            serviceConnection: sc-cohort-manager-dev
            testProjectDirectory: 'tests/playwright-tests'
            testfileDirectory: 'src/tests/e2e/testFiles'
            testProjectName: 'tests'
            testType: 'regression:e2e:epic2'

    # Regression E2E Epic3 Tests Job
    - job: regression_e2e_epic3_tests
      displayName: Run Regression E2E Epic3 Tests
      pool:
        name: private-pool-dev-uks
      steps:
        - template: .azuredevops/templates/steps/run-post-deployment-pw-tests.yaml@dtos-devops-templates
          parameters:
            serviceConnection: sc-cohort-manager-dev
            testProjectDirectory: 'tests/playwright-tests'
            testfileDirectory: 'src/tests/e2e/testFiles'
            testProjectName: 'tests'
            testType: 'regression:e2e:epic3'
