---

name: $(Build.SourceBranchName)-$(Date:yyyyMMdd)_$(Rev:r)
trigger: none
pr: none

resources:
  repositories:
  - repository: dtos-devops-templates
    type: github
    name: NHSDigital/dtos-devops-templates
    ref: 7dd6e83de82475570a27e172b95be8d30f488695
    endpoint: NHSDigital

variables:
- group: DEV_automation_testing_pipeline

parameters:
- name: destEnvironmentShortName
  displayName: Destination Environment Short Name
  type: string
  values:
  - dev
  default: dev

stages:
- stage: post_deployment_tests_stage
  displayName: Post-deployment tests

  variables:
  - name: TARGET_ENVIRONMENT
    value: ${{ parameters.destEnvironmentShortName }}

  jobs:
  - job: post_deployment_tests
    displayName: Run post-deployment tests
    pool:
      name: private-pool-prod-uks
    variables:
      AppSettings.ConnectionStrings.DtOsDatabaseConnectionString: $(DTOS_DATABASE_CONNECTION_STRING)
      AppSettings.AzureWebJobsStorage: $(CAASFOLDER_STORAGE_CONNECTION_STRING)

    steps:
    - template: ../templates/steps/run-post-deployment-tests.yaml
      parameters:
        serviceConnection: sc-cohort-manager-dev
