---

name: $(Build.SourceBranchName)-$(Date:yyyyMMdd)_$(Rev:r)
trigger: none
pr: none

pool:
  name: private-pool-dev-uks

schedules:
  - cron: "0 7 * * *" # Run at 7:00 AM UTC
    displayName: 'Scale_Peak'
    branches:
      include:
      - main
    always: true

  - cron: "0 17 * * *" # Run at 5:00 PM UTC
    displayName: 'Scale_OffPeak'
    branches:
      include:
      - main
    always: true

resources:
  repositories:
    - repository: dtos-devops-templates
      type: github
      name: NHSDigital/dtos-devops-templates
      ref: aa5e5fa9f2e4c95a72993af0ac6bef51142463bd
      endpoint: NHSDigital

parameters:
  - name: manualOverride
    displayName: Manual Override
    type: string
    default: 'false'
    values:
    - 'false'
    - 'Scale_Peak'
    - 'Scale_OffPeak'
  - name: Sku_Peak
    displayName: Peak SKU
    type: string
    default: 'S1'
  - name: Sku_OffPeak
    displayName: Off-Peak SKU
    type: string
    default: 'S0'

variables:
  - group: INT_core_backend

stages:
- template: ../templates/task-azure-sql-scaling-common.yaml
  parameters:
    manualOverride: ${{ parameters.manualOverride }}
    Sku_Peak: ${{ parameters.Sku_Peak }}
    Sku_OffPeak:  ${{ parameters.Sku_OffPeak }}
