# SEE: https://github.com/gitleaks/gitleaks/#configuration

[extend]
useDefault = true # SEE: https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml

[[rules]]
description = "IPv4"
id = "ipv4"
regex = '''[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'''

[rules.allowlist]
regexTarget = "match"
regexes = [
  # Exclude the private network IPv4 addresses as well as the DNS servers for Google and OpenDNS
  '''(127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}|10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}|172\.(1[6-9]|2[0-9]|3[0-1])\.[0-9]{1,3}\.[0-9]{1,3}|192\.168\.[0-9]{1,3}\.[0-9]{1,3}|0\.0\.0\.0|255\.255\.255\.255|8\.8\.8\.8|8\.8\.4\.4|208\.67\.222\.222|208\.67\.220\.220)''',
]

[allowlist]
paths = [
  '''.terraform.lock.hcl''',
  '''poetry.lock''',
  '''yarn.lock''',
  '''docs/guides/Perform_static_analysis.md''',
  '''.sln''',
  '''application/CohortManager/spikes/AzureLocalSimulators/DTOS-2460_Event_Grid_Spike/templates/Azure EG Topic - createParticipant/parameters.json''',
  '''application/CohortManager/spikes/AzureLocalSimulators/DTOS-2460_Event_Grid_Spike/templates/Azure EG Topic - createParticipant/template.json''',
  '''application/CohortManager/spikes/AzureLocalSimulators/DTOS-2460_Event_Grid_Spike/templates/Azure Sql Template/parameters.json''',
  '''application/CohortManager/spikes/AzureLocalSimulators/DTOS-2460_Event_Grid_Spike/templates/Azure Sql Template/template.json''',
  '''application/CohortManager/src/Functions/CaasIntegration/receiveCaasFile/receiveCaasFile.csproj''',
  '''tests/CaasIntegrationTests/receiveCaasFileTest/receiveCaasFileTest.csproj''',
  '''tests/IntegrationTests/integration.csproj''',
  '''application/CohortManager/src/Functions/Shared/Model/Model.csproj''',
  '''tests/smoke-tests/dtos-cohort-manager-smoke-tests/''',
'''tests/e2e-tests/NHS.CohortManager.EndToEndTests/NHS.CohortManager.EndToEndTests.csproj''',
'''tests/e2e-tests/dtos-cohort-manager-e2e-tests/dtos_cohort_manager_e2e_tests.csproj'''
]


[[rules]]
description = "Slack Webhook URL"
regex = '''https://hooks\.slack\.com/services/[A-Z0-9]{12}/[A-Z0-9]{12}/[A-Za-z0-9]{25}'''
tags = ["webhook", "slack"]

[[allowlist.rules]]
description = "Allow known non-secret CIS2 client IDs for Terraform environments"
regex = '''[0-9]{10}\.cohort-.*\.b099494b-7c49-4d78-9e3c-3a801aac691b\.apps'''
paths = [
    '''infrastructure/tf-core/environments/'''
]
commits = [
    "ae891c5d4a60e474e276a0508d673ccaacbe3741",
    "83bf708e6acd6702154b30b6cdda6a31379354b2",
    "1d81e8480afdbe7ed21aa9c0b5277ca575d7931e",
    "3e3de2e638cf80ec7a0a131b51ae5b9e43b21703",
    "cd007c859876b2e821643b589cecbf803329e580",
    "b12b384c5e078b4961883fcf07637c0ea059f8a1",
    "b8c4ad2837baf6bc27c155d64cf96a1f0df6e2f1",
    "3dbd42403f6780da44a998e708f2ef2d16821577",
    "3c5e0b8ecd5b683640823dd8e63f192d52065335"
]
