ALTER DATABASE DToSDB SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 7 DAYS, AUTO_CLEANUP = ON);
ALTER TABLE dbo.ADDRESS ENABLE CHANGE_TRACKING;
ALTER TABLE dbo.COHORT ENABLE CHANGE_TRACKING;
ALTER TABLE dbo.CONTACT_PREFERENCE ENABLE CHANGE_TRACKING;
ALTER TABLE dbo.GENDER_MASTER ENABLE CHANGE_TRACKING;
ALTER TABLE dbo.PARTICIPANT ENABLE CHANGE_TRACKING;
ALTER TABLE dbo.SCREENING_PROGRAMS ENABLE CHANGE_TRACKING;
