ALTER DATABASE DevDToSDB SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 7 DAYS, AUTO_CLEANUP = ON);
ALTER TABLE ADDRESS ENABLE CHANGE_TRACKING;
ALTER TABLE COHORT ENABLE CHANGE_TRACKING;
ALTER TABLE CONTACT_PREFERENCE ENABLE CHANGE_TRACKING;
ALTER TABLE GENDER_MASTER ENABLE CHANGE_TRACKING;
ALTER TABLE PARTICIPANT ENABLE CHANGE_TRACKING;
ALTER TABLE SCREENING_PROGRAMS ENABLE CHANGE_TRACKING;
