---

parameters:
- name: serviceConnection
  type: string

steps:

- task: Bash@3
  displayName: 'Output Pipeline Variables for Debugging'
  inputs:
    targetType: 'inline'
    script: |
      echo "Performing debugging steps"
      # nslookup sqlsvr-cohman-dev-uks.database.windows.net 10.100.7.4

- task: UseDotNet@2
  displayName: 'Use .NET 9 SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    includePreviewVersions: true

- task: DeleteFiles@1
  displayName: 'Clean Build Directory'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      **/bin/*
      **/obj/*
      **/TestResults/*
      **/drop/*
    RemoveSourceFolder: false

- task: Bash@3
  displayName: 'Print appsettings.json before variable substitution'
  inputs:
    targetType: 'inline'
    script: |
      cat $(Build.SourcesDirectory)/tests/smoke-tests/dtos-cohort-manager-smoke-tests/Config/appsettings.json

- task: FileTransform@1
  displayName: 'Transform Configuration Files'
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/tests/smoke-tests/dtos-cohort-manager-smoke-tests/Config'
    fileType: 'json'
    targetFiles: '*.json'

- task: Bash@3
  displayName: 'Print appsettings.json after variable substitution'
  inputs:
    targetType: 'inline'
    script: |
      cat $(Build.SourcesDirectory)/tests/smoke-tests/dtos-cohort-manager-smoke-tests/Config/appsettings.json

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/tests/smoke-tests/dtos-cohort-manager-smoke-tests/TestFiles'
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/TestFiles'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'TestFiles'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'TestFiles'
    downloadPath: '$(System.DefaultWorkingDirectory)'

- task: DotNetCoreCLI@2
  displayName: 'Build Smoke Tests Solution'
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/tests/smoke-tests/dtos-cohort-manager-smoke-tests.sln'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Run SpecFlow Tests'
  inputs:
    command: 'test'
    projects: '$(System.DefaultWorkingDirectory)/tests/smoke-tests/dtos-cohort-manager-smoke-tests/dtos-cohort-manager-smoke-tests.csproj'
    publishTestResults: true
    azureSubscription: sc-cohort-manager-dev

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/SpecFlowResults.trx'
    testRunTitle: 'SpecFlow Tests'
    mergeTestResults: true
    createTestRun: true
    testResultFormat: VSTest
    azureSubscription: sc-cohort-manager-dev
