parameters:
 - name: serviceConnection
   type: string


steps:
 - checkout: self
   fetchDepth: 1

 - task: UseDotNet@2
   displayName: 'Use .NET 9 SDK'
   inputs:
     packageType: 'sdk'
     version: '9.0.x'
     includePreviewVersions: true

 - task: FileTransform@1
   displayName: 'Transform Configuration Files'
   inputs:
     folderPath: '$(System.DefaultWorkingDirectory)/dtos-cohort-manager/tests/smoke-tests'
     fileType: 'json'
     targetFiles: '**/appsettings.json'
   env:
     AzureWebJobsStorage: $(AzureWebJobsStorage)
     AppSettings.ConnectionStrings.DtOsDatabaseConnectionString: $(SqlServerConnectionString)

 - task: DotNetCoreCLI@2
   displayName: 'Build Smoke Tests Solution'
   inputs:
     command: 'build'
     projects: '$(Build.SourcesDirectory)/dtos-cohort-manager/tests/smoke-tests/dtos-cohort-manager-smoke-tests.sln'
     arguments: '--configuration Release'

 - task: DotNetCoreCLI@2
   displayName: 'Run SpecFlow Tests'
   inputs:
     command: 'test'
     projects: '$(System.DefaultWorkingDirectory)/dtos-cohort-manager/tests/smoke-tests/dtos-cohort-manager-smoke-tests/dtos-cohort-manager-smoke-tests.csproj'
     publishTestResults: true

 - task: PublishTestResults@2
   displayName: 'Publish Test Results'
   condition: succeededOrFailed()
   inputs:
     testResultsFiles: '**/SpecFlowResults.trx'
     testRunTitle: 'SpecFlow Tests'
     mergeTestResults: true
     createTestRun: true
     testResultFormat: 'VSTest'
