import { RuleMapping } from "@/app/types";

export const ruleIdMappings: Record<number, RuleMapping> = {
  0: {
    ruleDescription: "System exception",
    moreDetails: "This exception was generated by the system during file processing or other automated operations.",
    reportingId: undefined,
  },
  1: {
    ruleDescription: "Transform data service error",
    moreDetails: "An error occurred during data transformation, such as generating a dummy GP practice code.",
    reportingId: undefined,
  },
  3: {
    ruleDescription:
      "It's not possible to have both a current GP practice code and a current reason for removal (RfR), or neither.",
    moreDetails:
      "Either: enter a GP practice code, or enter a reason for removal. Information must only be entered for one of these fields. Both fields cannot be empty.",
    reportingId: "CMR13",
  },
  8: {
    ruleDescription:
      "Record from CaaS is either missing from or is not recognised by Cohort Manager.",
    moreDetails: "Raise with Cohorting as a Service (CaaS).",
    reportingId: "CMR4",
    portalFormTitle: "Raise with Cohorting as a Service (CaaS)",
  },
  17: {
    ruleDescription:
      "Date of birth is either missing, in the wrong format, or is in the future.",
    moreDetails:
      "Enter the date of birth in the correct format. The date must not be in the future. ",
    reportingId: "CMR14",
  },
  18: {
    ruleDescription:
      "Date of death is in the wrong format or is in the future.",
    moreDetails:
      "Enter the date of death in the correct format. The date cannot be in the future.",
    reportingId: "CMR22",
  },
  30: {
    ruleDescription: "Postcode is in the wrong format.",
    moreDetails: "Enter a valid UK postcode.",
    reportingId: "CMR12",
  },
  35: {
    ruleDescription:
      "Possible Confusion. At least 2 of the following have changed: family name, gender or date of birth",
    moreDetails:
      "Verify that the changes are correct, and that the NHS number is not involved in a confusion case.",
    reportingId: "CMR38",
  },
  39: {
    ruleDescription: "Missing surname.",
    moreDetails: "Enter the patient's surname.",
    reportingId: "CMR15",
  },
  40: {
    ruleDescription: "Missing forename.",
    moreDetails: "Enter the patient's forename.",
    reportingId: "CMR16",
  },
  45: {
    ruleDescription: "GP practice code does not exist",
    moreDetails: `National Service Desk (NSD) action: Raise with Breast Screening Select second line, including the following information.
We were unable to process this record as the GP practice is not mapped to a breast screening office (BSO). This may be because it’s a new or split practice.
To resolve this, please:
check the GP practice details for errors
if correct, assign the GP practice to the appropriate BSO in the organisational table (BSO-GP mapping table) `,
    reportingId: "CMR45",
    portalFormTitle: "Raise with Breast Screening Select second line",
  },
  49: {
    ruleDescription: "Interpreter required information is not valid",
    moreDetails:
      "The interpreter required details must be entered as numbers 0 or 1. Check if an interpreter is needed for the participant: enter 0 if an interpreter is not required. Enter 1 if an interpreter is required",
    reportingId: "CMR49",
  },
  51: {
  ruleDescription: "Participant location remaining outside of cohort",
  moreDetails: "Resident in not included area in cohort moving to same or another area not included in cohort.",
  reportingId: "CMR51",
  },
  53: {
    ruleDescription: "Current posting awaiting update",
    moreDetails:
      "The patient’s GP practice code has been updated, but the current posting is yet to be updated",
    reportingId: "CMR53",
  },
  54: {
    ruleDescription:
      "A dummy GP practice code could not be generated. An English postcode must be entered.",
    moreDetails:
      "A dummy GP practice code is used by breast screening offices when a participant’s actual GP practice information is unknown. The relevant dummy GP practice code will be generated when a postcode is added to the record.",
    reportingId: "CMR34",
  },
  66: {
    ruleDescription:
      "NHS number has been marked as formally dead, but the reason for removal (RfR) is not ‘DEA’.",
    moreDetails:
      "To update a record with a formal death status, ensure that the reason for removal field contains a compatible death-related value.",
    reportingId: "CMR20",
    portalFormTitle: "Confused NHS numbers",
  },
  71: {
    ruleDescription: "Address is blank (postcode may be blank too).",
    moreDetails: "Enter the patient's full address and postcode.",
    reportingId: "CMR17",
  },
  98: {
    ruleDescription: "Participant cannot be sent to BS Select due to reason for removal (RfR).",
    moreDetails: `National Service Desk (NSD) action: Raise with Breast Screening Select second line, including the following information.
A request to manually add a participant could not be sent to BS Select.
We checked the participant’s PDS record and found a reason for removal (RfR) code that BS Select will not accept.

The record contains one of the following RfR codes:

AFL (armed forces enlistment - notified locally)
AFN (armed forces enlistment – notified by armed forces)
DEA (death)
LDN (logical deletion)
SDL (services dependant – notified locally)
SDN (service dependant – notified by SMO)
TRA (temporary resident not returned)

Please contact the Breast Screening Office (BSO) that submitted the referral and explain why we are unable to add the participant to BS Select. `,
    reportingId: "CMR98",
    portalFormTitle: "Raise with Breast Screening Select second line",
  },
  97: {
    ruleDescription: "Missing GP details.",
    moreDetails: `National Service Desk (NSD) action:

Raise with Breast Screening Select second line, including the following information.

A request to manually add a participant could not be sent to BS Select as it does not contain GP details or a dummy GP code.

Please check the record. A valid GP code or a dummy GP code must be entered to send the participant to BS Select. `,
    reportingId: "CMR97",
    portalFormTitle: "Raise with Breast Screening Select second line",
  },
  3601:{
    ruleDescription: "GP practice not mapped to a breast screening office (BSO).",
    moreDetails: `National Service Desk (NSD) action: Raise with Breast Screening Select second line, including the following information.

A request to manually add a participant could not be processed as the GP practice code is not mapped to a breast screening office (BSO).

If the GP practice code is correct, it may not be mapped to a BSO because it is a new or split practice.

Check the GP practice code and add it to the organisational table (BSO-GP mapping table) if needed.`,
    reportingId: "CMR40",
    portalFormTitle: "Raise with Breast Screening Select second line",
  },
};

export function getRuleMapping(
  ruleId: number,
  fallbackDescription?: string
): RuleMapping {
  return (
    ruleIdMappings[ruleId] || {
      ruleDescription: fallbackDescription,
      moreDetails: fallbackDescription,
      reportingId: undefined,
    }
  );
}
