/*==============================================================*/
/* Table: BS_COHORT_DISTRIBUTION                                */
/*==============================================================*/
IF NOT EXISTS
(
    SELECT *
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
          AND TABLE_NAME = 'BS_COHORT_DISTRIBUTION'
)
BEGIN
    CREATE TABLE BS_COHORT_DISTRIBUTION (
        BS_COHORT_DISTRIBUTION_ID INT IDENTITY(1,1) NOT NULL,
        PARTICIPANT_ID BIGINT NULL,
        NHS_NUMBER BIGINT NULL,
        SUPERSEDED_NHS_NUMBER BIGINT NULL,
        PRIMARY_CARE_PROVIDER VARCHAR(10) NULL,
        PRIMARY_CARE_PROVIDER_FROM_DT DATE NULL,
        NAME_PREFIX VARCHAR(35) NULL,
        GIVEN_NAME VARCHAR(100) NULL,
        OTHER_GIVEN_NAME VARCHAR(100) NULL,
        FAMILY_NAME VARCHAR(100) NULL,
        PREVIOUS_FAMILY_NAME VARCHAR(100) NULL,
        DATE_OF_BIRTH DATE NULL,
        GENDER SMALLINT NULL,
        ADDRESS_LINE_1 VARCHAR(100) NULL,
        ADDRESS_LINE_2 VARCHAR(100) NULL,
        ADDRESS_LINE_3 VARCHAR(100) NULL,
        ADDRESS_LINE_4 VARCHAR(100) NULL,
        ADDRESS_LINE_5 VARCHAR(100) NULL,
        POST_CODE VARCHAR(10) NULL,
        USUAL_ADDRESS_FROM_DT DATE NULL,
        CURRENT_POSTING VARCHAR(10) NULL,
        CURRENT_POSTING_FROM_DT DATE NULL,
        DATE_OF_DEATH DATE NULL,
        TELEPHONE_NUMBER_HOME VARCHAR(35) NULL,
        TELEPHONE_NUMBER_HOME_FROM_DT DATE NULL,
        TELEPHONE_NUMBER_MOB VARCHAR(35) NULL,
        TELEPHONE_NUMBER_MOB_FROM_DT DATE NULL,
        EMAIL_ADDRESS_HOME VARCHAR(100) NULL,
        EMAIL_ADDRESS_HOME_FROM_DT DATE NULL,
        PREFERRED_LANGUAGE VARCHAR(35) NULL,
        INTERPRETER_REQUIRED SMALLINT NULL,
        REASON_FOR_REMOVAL VARCHAR(10) NULL,
        REASON_FOR_REMOVAL_FROM_DT DATE NULL,
        IS_EXTRACTED SMALLINT NULL,
        RECORD_INSERT_DATETIME DATETIME NULL,
        RECORD_UPDATE_DATETIME DATETIME NULL,
        REQUEST_ID uniqueidentifier NULL,
        constraint BS_COHORT_DISTRIBUTION_PK
            primary key (BS_COHORT_DISTRIBUTION_ID)
    );
END

/*==============================================================*/
/* Table: GENDER_MASTER                                         */
/*==============================================================*/
IF NOT EXISTS
(
    SELECT *
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
          AND TABLE_NAME = 'GENDER_MASTER'
)
BEGIN
    CREATE TABLE dbo.GENDER_MASTER
    (
        GENDER_CD VARCHAR(2) NOT NULL,
        GENDER_DESC VARCHAR(10) NULL,
        CONSTRAINT PK_GENDER_MASTER
            PRIMARY KEY (GENDER_CD)
    );
END

/*==============================================================*/
/* Table: PARTICIPANT_DEMOGRAPHIC                               */
/*==============================================================*/
IF NOT EXISTS
(
    SELECT *
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
          AND TABLE_NAME = 'PARTICIPANT_DEMOGRAPHIC'
)
BEGIN
    CREATE TABLE dbo.PARTICIPANT_DEMOGRAPHIC
    (
        PARTICIPANT_ID BIGINT IDENTITY(1, 1) NOT NULL,
        NHS_NUMBER BIGINT NULL,
        SUPERSEDED_BY_NHS_NUMBER BIGINT NULL,
        PRIMARY_CARE_PROVIDER VARCHAR(10) NULL,
        PRIMARY_CARE_PROVIDER_FROM_DT VARCHAR(8) NULL,
        CURRENT_POSTING VARCHAR(10) NULL,
        CURRENT_POSTING_FROM_DT VARCHAR(8) NULL,
        NAME_PREFIX VARCHAR(35) NULL,
        GIVEN_NAME VARCHAR(100) NULL,
        OTHER_GIVEN_NAME VARCHAR(100) NULL,
        FAMILY_NAME VARCHAR(100) NULL,
        PREVIOUS_FAMILY_NAME VARCHAR(100) NULL,
        DATE_OF_BIRTH VARCHAR(10) NULL,
        GENDER SMALLINT NULL,
        ADDRESS_LINE_1 VARCHAR(100) NULL,
        ADDRESS_LINE_2 VARCHAR(100) NULL,
        ADDRESS_LINE_3 VARCHAR(100) NULL,
        ADDRESS_LINE_4 VARCHAR(100) NULL,
        ADDRESS_LINE_5 VARCHAR(100) NULL,
        POST_CODE VARCHAR(10) NULL,
        PAF_KEY VARCHAR(10) NULL,
        USUAL_ADDRESS_FROM_DT VARCHAR(8) NULL,
        DATE_OF_DEATH VARCHAR(10) NULL,
        DEATH_STATUS SMALLINT NULL,
        TELEPHONE_NUMBER_HOME VARCHAR(35) NULL,
        TELEPHONE_NUMBER_HOME_FROM_DT VARCHAR(8) NULL,
        TELEPHONE_NUMBER_MOB VARCHAR(35) NULL,
        TELEPHONE_NUMBER_MOB_FROM_DT VARCHAR(8) NULL,
        EMAIL_ADDRESS_HOME VARCHAR(100) NULL,
        EMAIL_ADDRESS_HOME_FROM_DT VARCHAR(8) NULL,
        PREFERRED_LANGUAGE VARCHAR(35) NULL,
        INTERPRETER_REQUIRED SMALLINT NULL,
        INVALID_FLAG SMALLINT NULL,
        RECORD_INSERT_DATETIME DATETIME NULL,
        RECORD_UPDATE_DATETIME DATETIME NULL,
        CONSTRAINT PK_PARTICIPANT_DEMOGRAPHIC
            PRIMARY KEY (PARTICIPANT_ID)
    );
END


/*==============================================================*/
/* Table: SCREENING_LKP                                         */
/*==============================================================*/
IF NOT EXISTS
(
    SELECT *
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
          AND TABLE_NAME = 'SCREENING_LKP'
)
BEGIN
    CREATE TABLE SCREENING_LKP
    (
        SCREENING_ID BIGINT IDENTITY(1, 1) NOT NULL,
        SCREENING_NAME VARCHAR(50) NULL,
        SCREENING_TYPE VARCHAR(50) NULL,
        SCREENING_ACRONYM    VARCHAR(50) NULL,
        SCREENING_WORKFLOW_ID VARCHAR(50) NULL
        CONSTRAINT PK_SCREENING_LKP
            PRIMARY KEY (SCREENING_ID)
    );
END

/*==============================================================*/
/* Table: PARTICIPANT_MANAGEMENT                                */
/*==============================================================*/

IF NOT EXISTS
(
    SELECT *
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
    AND TABLE_NAME = 'PARTICIPANT_MANAGEMENT'
)
BEGIN
    CREATE TABLE PARTICIPANT_MANAGEMENT
    (
        PARTICIPANT_ID BIGINT IDENTITY(1,1) NOT NULL,
        SCREENING_ID BIGINT NOT NULL,
        NHS_NUMBER BIGINT NOT NULL,
        RECORD_TYPE VARCHAR(10) NULL,
        ELIGIBILITY_FLAG SMALLINT NULL,
        REASON_FOR_REMOVAL VARCHAR(10) NULL,
        REASON_FOR_REMOVAL_FROM_DT DATE NULL,
        BUSINESS_RULE_VERSION VARCHAR (10) NULL,
        EXCEPTION_FLAG SMALLINT  NULL,
        RECORD_INSERT_DATETIME DATETIME NULL,
        RECORD_UPDATE_DATETIME DATETIME NULL,
        NEXT_TEST_DUE_DATE DATE NULL,
        NEXT_TEST_DUE_DATE_CALC_METHOD VARCHAR(100) NULL,
        PARTICIPANT_SCREENING_STATUS VARCHAR(100) NULL,
        SCREENING_CEASED_REASON VARCHAR(100) NULL,
        IS_HIGHER_RISK SMALLINT NULL,
        IS_HIGHER_RISK_ACTIVE SMALLINT NULL,
        HIGHER_RISK_NEXT_TEST_DUE_DATE DATE NULL,
        HIGHER_RISK_REFERRAL_REASON_ID BIGINT NULL,
        DATE_IRRADIATED DATE NULL,
        GENE_CODE_ID BIGINT NULL,
        SRC_SYSTEM_PROCESSED_DATETIME DATETIME NULL,
        CONSTRAINT PK_PARTICIPANT_MANAGEMENT
            PRIMARY KEY (PARTICIPANT_ID),
        CONSTRAINT FK_PARTICIP_SCREENING_SCREENIN
        FOREIGN KEY (SCREENING_ID)
        REFERENCES SCREENING_LKP (SCREENING_ID),
        CONSTRAINT UC_NHS_SCREENING UNIQUE (SCREENING_ID,NHS_NUMBER)
    );
END

/*==============================================================*/
/* Table: EXCEPTION_MANAGEMENT                                  */
/*==============================================================*/
IF NOT EXISTS
(
    SELECT *
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
          AND TABLE_NAME = 'EXCEPTION_MANAGEMENT'
)
BEGIN
    CREATE TABLE [dbo].[EXCEPTION_MANAGEMENT]
    (
        EXCEPTION_ID INT IDENTITY(1,1) NOT NULL,
        FILE_NAME VARCHAR(250) NULL,
        NHS_NUMBER VARCHAR(50) NULL,
        DATE_CREATED DATETIME NULL,
        DATE_RESOLVED DATE NULL,
        RULE_ID INT NULL,
        RULE_DESCRIPTION NVARCHAR(MAX) NULL,
        ERROR_RECORD NVARCHAR(MAX) NULL,
        CATEGORY INT NULL,
        SCREENING_NAME VARCHAR(100) NULL,
        EXCEPTION_DATE DATE NULL,
        COHORT_NAME VARCHAR(100) NULL,
        IS_FATAL SMALLINT NULL
    );
END

/*==============================================================*/
/* Table: BS_SELECT_GP_PRACTICE_LKP                             */
/*==============================================================*/
IF NOT EXISTS
(
    SELECT *
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
          AND TABLE_NAME = 'BS_SELECT_GP_PRACTICE_LKP'
)
BEGIN
CREATE TABLE [dbo].[BS_SELECT_GP_PRACTICE_LKP]
    (
      GP_PRACTICE_CODE VARCHAR(8),
      BSO VARCHAR(4),
      COUNTRY_CATEGORY VARCHAR(15),
      AUDIT_ID NUMERIC(38),
      AUDIT_CREATED_TIMESTAMP DATETIME,
      AUDIT_LAST_MODIFIED_TIMESTAMP DATETIME,
      AUDIT_TEXT VARCHAR(50)
    );
END

/*==============================================================*/
/* Table: BS_SELECT_OUTCODE_MAPPING_LKP                         */
/*==============================================================*/
IF NOT EXISTS
(
    SELECT *
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
          AND TABLE_NAME = 'BS_SELECT_OUTCODE_MAPPING_LKP'
)
BEGIN
CREATE TABLE [dbo].[BS_SELECT_OUTCODE_MAPPING_LKP]
    (
      OUTCODE VARCHAR(4) PRIMARY KEY,
      BSO VARCHAR(4),
      AUDIT_ID NUMERIC(38),
      AUDIT_CREATED_TIMESTAMP DATETIME,
      AUDIT_LAST_MODIFIED_TIMESTAMP DATETIME,
      AUDIT_TEXT VARCHAR(50)
    );
END

/*==============================================================*/
/* Table: BS_SELECT_REQUEST_AUDIT Table                       */
/*==============================================================*/
IF NOT EXISTS
(
    SELECT *
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
          AND TABLE_NAME = 'BS_SELECT_REQUEST_AUDIT'
)
BEGIN
CREATE TABLE [dbo].[BS_SELECT_REQUEST_AUDIT]
    (
      REQUEST_ID UNIQUEIDENTIFIER NOT NULL,
      STATUS_CODE VARCHAR(3) NULL,
      CREATED_DATETIME DATETIME NULL,
    );
END

/*==============================================================*/
/* Table: GP_PRACTICES                                          */
/*==============================================================*/
IF NOT EXISTS
(
    SELECT *
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
          AND TABLE_NAME = 'GP_PRACTICES'
)

BEGIN
CREATE TABLE GP_PRACTICES
(
    GP_PRACTICE_ID INT IDENTITY PRIMARY KEY,
    GP_PRACTICE_CODE varchar(8) NOT NULL,
    BSO_ORGANISATION_ID integer NOT NULL,
    OUTCODE varchar(4),
    GP_PRACTICE_GROUP_ID integer,
    TRANSACTION_ID integer NOT NULL,
    TRANSACTION_APP_DATE_TIME datetimeoffset NOT NULL,
    TRANSACTION_USER_ORG_ROLE_ID integer NOT NULL,
    TRANSACTION_DB_DATE_TIME datetimeoffset NOT NULL,
    GP_PRACTICE_NAME varchar(100),
    ADDRESS_LINE_1 varchar(35),
    ADDRESS_LINE_2 varchar(35),
    ADDRESS_LINE_3 varchar(35),
    ADDRESS_LINE_4 varchar(35),
    ADDRESS_LINE_5 varchar(35),
    POSTCODE varchar(8),
    TELEPHONE_NUMBER varchar(12),
    OPEN_DATE date,
    CLOSE_DATE date,
    FAILSAFE_DATE date,
    STATUS_CODE varchar(1) NOT NULL,
    LAST_UPDATED_DATE_TIME datetimeoffset NOT NULL,
    ACTIONED BIT NOT NULL DEFAULT 0,
    LAST_ACTIONED_BY_USER_ORG_ROLE_ID integer,
    LAST_ACTIONED_ON datetimeoffset
)
END

/*==============================================================*/
/* Table: EXCLUDED_SMU_LKP                                      */
/*==============================================================*/
IF NOT EXISTS
(
    SELECT *
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
          AND TABLE_NAME = 'EXCLUDED_SMU_LKP'
)

BEGIN
CREATE TABLE EXCLUDED_SMU_LKP
(
    GP_PRACTICE_CODE VARCHAR(8) PRIMARY KEY
);
END

/*==============================================================*/
/* Table: CURRENT_POSTING_LKP                                   */
/*==============================================================*/
IF NOT EXISTS
(
    SELECT *
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
          AND TABLE_NAME = 'CURRENT_POSTING_LKP'
)

CREATE TABLE CURRENT_POSTING_LKP
(
    POSTING VARCHAR(4) PRIMARY KEY,
    IN_USE VARCHAR(1),
    INCLUDED_IN_COHORT VARCHAR(1),
    POSTING_CATEGORY VARCHAR(10)
);

/*==============================================================*/
/* Table: LANGUAGE_CODES                                        */
/*==============================================================*/
IF NOT EXISTS
(
    SELECT *
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
          AND TABLE_NAME = 'LANGUAGE_CODES'
)

CREATE TABLE LANGUAGE_CODES
(
    LANGUAGE_CODE VARCHAR(2) PRIMARY KEY,
    LANGUAGE_DESCRIPTION VARCHAR(100)
);

/*==============================================================*/
/* Table: BSO_ORGANISATIONS Table                               */
/*==============================================================*/
IF NOT EXISTS
(
    SELECT *
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
          AND TABLE_NAME = 'BSO_ORGANISATIONS'
)
BEGIN
    CREATE TABLE [dbo].[BSO_ORGANISATIONS]
    (
      BSO_ORGANISATION_ID INT IDENTITY(1,1) PRIMARY KEY,
      BSO_ORGANISATION_CODE VARCHAR(4) NOT NULL,
      BSO_ORGANISATION_NAME VARCHAR(60) NOT NULL,
      SAFETY_PERIOD TINYINT NOT NULL,
      RISP_RECALL_INTERVAL TINYINT NOT NULL,
      TRANSACTION_ID INT NOT NULL,
      TRANSACTION_APP_DATE_TIME DATETIME NOT NULL,
      TRANSACTION_USER_ORG_ROLE_ID INT NOT NULL,
      TRANSACTION_DB_DATE_TIME DATE NOT NULL,
      IGNORE_SELF_REFERRALS BIT NOT NULL,
      IGNORE_GP_REFERRALS BIT NOT NULL,
      IGNORE_EARLY_RECALL BIT NOT NULL,
      IS_ACTIVE BIT NOT NULL,
      LOWER_AGE_RANGE TINYINT NOT NULL,
      UPPER_AGE_RANGE TINYINT NOT NULL,
      LINK_CODE VARCHAR(10) NOT NULL,
      FOA_MAX_OFFSET TINYINT NOT NULL,
      BSO_RECALL_INTERVAL TINYINT NOT NULL,
      ADDRESS_LINE_1 VARCHAR(35),
      ADDRESS_LINE_2 VARCHAR(35),
      ADDRESS_LINE_3 VARCHAR(35),
      ADDRESS_LINE_4 VARCHAR(35),
      ADDRESS_LINE_5 VARCHAR(35),
      POSTCODE VARCHAR(8),
      TELEPHONE_NUMBER VARCHAR(18),
      EXTENSION VARCHAR(6),
      FAX_NUMBER VARCHAR(18),
      EMAIL_ADDRESS VARCHAR(100),
      OUTGOING_TRANSFER_NUMBER INT NOT NULL,
      INVITE_LIST_SEQUENCE_NUMBER INT NOT NULL,
      FAILSAFE_DATE_OF_MONTH TINYINT NOT NULL,
      FAILSAFE_MONTHS TINYINT NOT NULL,
      FAILSAFE_MIN_AGE_YEARS TINYINT NOT NULL,
      FAILSAFE_MIN_AGE_MONTHS TINYINT NOT NULL,
      FAILSAFE_MAX_AGE_YEARS TINYINT NOT NULL,
      FAILSAFE_MAX_AGE_MONTHS TINYINT NOT NULL,
      FAILSAFE_LAST_RUN DATETIME NOT NULL,
      IS_AGEX BIT NOT NULL,
      IS_AGEX_ACTIVE BIT NOT NULL,
      AUTO_BATCH_LAST_RUN DATETIME,
      AUTO_BATCH_MAX_DATE_TIME_PROCESSED DATETIME,
      BSO_REGION_ID INT,
      ADMIN_EMAIL_ADDRESS VARCHAR(100),
      IEP_DETAILS VARCHAR(MAX),
      NOTES VARCHAR(MAX),
      RLP_DATE_ENABLED DATETIME
    );
END

/*==============================================================*/
/* Table: HIGHER_RISK_REFERRAL_REASON_LKP                       */
/*==============================================================*/
IF NOT EXISTS
(
    SELECT *
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
          AND TABLE_NAME = 'HIGHER_RISK_REFERRAL_REASON_LKP'
)
BEGIN
    CREATE TABLE [dbo].[HIGHER_RISK_REFERRAL_REASON_LKP]
    (
        HIGHER_RISK_REFERRAL_REASON_ID INT IDENTITY(1, 1) PRIMARY KEY,
        HIGHER_RISK_REFERRAL_REASON_CODE VARCHAR(100) NOT NULL,
        HIGHER_RISK_REFERRAL_REASON_CODE_DESCRIPTION VARCHAR(200) NULL
    );
END

/*==============================================================*/
/* Table: GENE_CODE_LKP                                         */
/*==============================================================*/
IF NOT EXISTS
(
    SELECT *
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
          AND TABLE_NAME = 'GENE_CODE_LKP'
)
BEGIN
    CREATE TABLE [dbo].[GENE_CODE_LKP]
    (
        GENE_CODE_ID INT IDENTITY(1, 1) PRIMARY KEY,
        GENE_CODE VARCHAR(100) NOT NULL,
        GENE_CODE_DESCRIPTION VARCHAR(200) NULL
    );
END

ALTER TABLE PARTICIPANT_MANAGEMENT
ADD CONSTRAINT FK_PARTICIP_REFERENCE_GENE_COD FOREIGN KEY (GENE_CODE_ID)
REFERENCES [dbo].[GENE_CODE_LKP] (GENE_CODE_ID);

ALTER TABLE PARTICIPANT_MANAGEMENT
ADD CONSTRAINT FK_PARTICIP_REFERENCE_HIGHER_R FOREIGN KEY (HIGHER_RISK_REFERRAL_REASON_ID)
REFERENCES [dbo].[HIGHER_RISK_REFERRAL_REASON_LKP] (HIGHER_RISK_REFERRAL_REASON_ID);
