FROM mcr.microsoft.com/dotnet/sdk:8.0 AS installer-env
COPY /DemographicServices/DemographicDurableFunction /src/dotnet-function-app
COPY ./Shared /Shared

RUN cd /src/dotnet-function-app && \
    dotnet restore && \
    mkdir -p /home/site/wwwroot && \
    dotnet publish *.csproj --output /home/site/wwwroot
RUN chmod -R 755 /home/site/wwwroot

FROM mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated8.0
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true
COPY --from=installer-env ["/home/site/wwwroot", "/home/site/wwwroot"]
RUN ls -la /home/site/wwwroot
