name: cohort-manager

services:
  gppractice-data-service:
    container_name: gppractice-data-service
    image: gppractice-data-service
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/GPPractice/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7910
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - AcceptableLatencyThresholdMs=500
      

  exception-management-data-service:
    container_name: exception-management-data-service
    image: exception-management-data-service
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/ExceptionManagementDataService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7911
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - AcceptableLatencyThresholdMs=500

  bs-request-audit-data-service:
    container_name: bs-request-audit-data-service
    image: bs-request-audit-data-service
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/BsSelectRequestAudit/Dockerfile
    profiles: [non-essential]
    environment:
      - ASPNETCORE_URLS=http://*:7989
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - AcceptableLatencyThresholdMs=500

  screening-lkp-data-service:
    container_name: screening-lkp-data-service
    image: screening-lkp-data-service
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/ScreeningLkpDataService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:8996
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - AcceptableLatencyThresholdMs=500
  bs-select-gp-practice-data-service:
    container_name: bs-select-gp-practice-data-service
    image: bs-select-gp-practice-data-service
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/BsSelectGpPractice/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7998
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=
      - AcceptableLatencyThresholdMs=500

  bs-select-outcode-data-service:
    container_name: bs-select-outcode-data-service
    image: bs-select-outcode-data-service
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/BsSelectOutCode/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7881
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - AcceptableLatencyThresholdMs=500

  language-code-data-service:
    container_name: language-code-data-service
    image: language-code-data-service
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/LanguageCodesDataService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7997
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - AcceptableLatencyThresholdMs=500

  current-posting-data-service:
    container_name: current-posting-data-service
    image: current-posting-data-service
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/CurrentPostingDataService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7996
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - AcceptableLatencyThresholdMs=500

  excluded-smu-data-service:
    container_name: excluded-smu-data-service
    image: excluded-smu-data-service
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/ExcludedSMULookupDataService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7995
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - AcceptableLatencyThresholdMs=500

  gene-code-lkp-data-service:
    container_name: gene-code-lkp-data-service
    image: gene-code-lkp-data-service
    networks: [cohman-network]
    profiles: [bi-analytics]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/GeneCodeLkpDataService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7991
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - AcceptableLatencyThresholdMs=500

  higher-risk-referral-reason-lkp-data-service:
    container_name: higher-risk-referral-reason-lkp-data-service
    image: higher-risk-referral-reason-lkp-data-service
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/HigherRiskReferralReasonLkpDataService/Dockerfile
    profiles: [bi-analytics]
    environment:
      - ASPNETCORE_URLS=http://*:7992
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - AcceptableLatencyThresholdMs=500

  participant-demographic-data-service:
    container_name: participant-demographic-data-service
    image: participant-demographic-data-service
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/ParticipantDemographicDataService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7993
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - AcceptableLatencyThresholdMs=500

  participant-management-data-service:
    container_name: participant-management-data-service
    image: participant-management-data-service
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/ParticipantManagementDataService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7994
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - AcceptableLatencyThresholdMs=500

  cohort-distribution-data-service:
    container_name: cohort-distribution-data-service
    image: cohort-distribution-data-service
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/CohortDistributionDataService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7992
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - AcceptableLatencyThresholdMs=500

networks:
  cohman-network:
    external: true