name: cohort-manager-deps

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    networks: [cohman-network]
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  azurite-setup:
    container_name: azurite-setup
    build:
      context: ./
      dockerfile: ./Set-up/azurite/Dockerfile
    networks: [cohman-network]
    depends_on:
      - azurite
    environment:
      - AZURITE_CONNECTION_STRING=${AZURITE_CONNECTION_STRING}

  mssql:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    networks: [cohman-network]
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${PASSWORD}
    cap_add:
      - SYS_PTRACE
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "${PASSWORD}" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  db-setup:
    container_name: db-setup
    build: ./Set-up/database
    networks: [cohman-network]
    depends_on:
      mssql:
        condition: service_healthy
    environment:
      - PASSWORD=${PASSWORD}
      - DB_NAME=${DB_NAME}
      - HOSTNAME=db

networks:
  cohman-network:
    name: cohman-network
    driver: bridge