name: cohort-manager

services:
  # CaaS Integration Service
  retrieve-mesh-file:
    container_name: retrieve-mesh-file
    image: cohort-manager-retrieve-mesh-file
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CaasIntegration/RetrieveMeshFile/Dockerfile
    profiles: [non-essential]
    environment:
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - caasfolder_STORAGE=${AZURITE_CONNECTION_STRING}
      - MeshApiBaseUrl=https://localhost:8700/messageexchange
      - BSSMailBox=X26ABC1
      - MeshPassword=${MESHPASSWORD}
      - MeshSharedKey=${MESHSHAREDKEY}
      - MeshKeyName=meshpfx.pfx
      - MeshKeyPassphrase=${MESHKEYPASSPHRASE}
      - ASPNETCORE_URLS=http://*:7059

  receive-caas-file:
    container_name: receive-caas-file
    image: cohort-manager-receive-caas-file
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CaasIntegration/receiveCaasFile/Dockerfile
    environment:
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - caasfolder_STORAGE=${AZURITE_CONNECTION_STRING}
      - ASPNETCORE_URLS=http://*:7060
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - DemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService
      - DemographicURI=http://durable-demographic-function:7079/api/DurableDemographicFunction_HttpStart
      - GetOrchestrationStatusURL=http://durable-demographic-function:7079/api/GetOrchestrationStatus
      - AllowDeleteRecords=true
      - BatchSize=3500
      - maxNumberOfChecks=50
      - recordThresholdForBatching=3
      - batchDivisionFactor=5
      - ScreeningLkpDataServiceURL=http://screening-lkp-data-service:8996/api/ScreeningLkpDataService
      - inboundBlobName=inbound
      - ServiceBusConnectionString_client_internal=Endpoint=sb://service-bus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - fileExceptions=file-exceptions
      - ParticipantManagementTopic=participant-management-topic

  # Participant Management Service
  manage-participant:
    container_name: manage-participant
    image: cohort-manager-manage-participant
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ParticipantManagementServices/ManageParticipant/Dockerfile
    environment:
      - ServiceBusConnectionString_internal=Endpoint=sb://service-bus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - ServiceBusConnectionString_client_internal=Endpoint=sb://service-bus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - CohortDistributionTopic=cohort-distribution-topic
      - ParticipantManagementTopic=participant-management-topic
      - ManageParticipantSubscription=manage-participant-sub
      - ParticipantManagementUrl=http://participant-management-data-service:7994/api/ParticipantManagementDataService
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException

  manage-servicenow-participant:
    container_name: manage-servicenow-participant
    image: cohort-manager-manage-servicenow-participant
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ParticipantManagementServices/ManageServiceNowParticipant/Dockerfile
    profiles: [service-now]
    environment:
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - ServiceNowParticipantManagementTopic=servicenow-participant-management-topic
      - ManageServiceNowParticipantSubscription=manage-servicenow-participant-sub
      - ServiceBusConnectionString_internal=Endpoint=sb://service-bus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - ServiceBusConnectionString_client_internal=Endpoint=sb://service-bus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - RetrievePdsDemographicURL=http://retrieve-pds-demographic:8082/api/RetrievePDSDemographic
      - SendServiceNowMessageURL=http://servicenow-message-handler:9092/api/servicenow/send
      - ParticipantManagementURL=http://participant-management-data-service:7994/api/ParticipantManagementDataService
      # - ManageNemsSubscriptionSubscribeURL=http://manage-nems-subscription:9081/api/Subscribe
      - ManageNemsSubscriptionSubscribeURL=http://manage-caas-subscription:9084/api/Subscribe
      - CohortDistributionTopic=cohort-distribution-topic

  update-blocked-flag:
    container_name: update-blocked-flag
    image: cohort-manager-update-blocked-flag
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ParticipantManagementServices/UpdateBlockedFlag/Dockerfile
    profiles: [non-essential]
    ports:
      - "7027:7027"
    environment:
      - ASPNETCORE_URLS=http://*:7027
      - AzureWebJobsStorage=UseDevelopmentStorage=true
      - ParticipantManagementUrl=http://participant-management-data-service:7994/api/ParticipantManagementDataService
      - ParticipantDemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService/
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      # - ManageNemsSubscriptionUnsubscribeURL=http://manage-nems-subscription:9081/api/Unsubscribe
      # - ManageNemsSubscriptionSubscribeURL=http://manage-nems-subscription:9081/api/Subscribe
      - ManageNemsSubscriptionUnsubscribeURL=http://manage-caas-subscription:9084/api/Unsubscribe
      - ManageNemsSubscriptionSubscribeURL=http://manage-caas-subscription:9084/api/Subscribe
      - RetrievePdsDemographicURL=http://etrieve-pds-demographic:8082/api/RetrievePdsDemographic

  delete-participant:
    container_name: delete-participant
    image: cohort-manager-delete-participant
    networks: [cohman-network]
    profiles: [non-essential]
    ports:
    - "7087:7087"
    build:
      context: ./src/Functions/
      dockerfile: ParticipantManagementServices/DeleteParticipant/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7087
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - CohortDistributionDataServiceURL=http://cohort-distribution-data-service:7992/api/CohortDistributionDataService/
      - AcceptableLatencyThresholdMs=500


  # Screening Data Service
  create-exception:
    container_name: create-exception
    image: cohort-manager-create-exception
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ExceptionHandling/CreateException/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7070
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - DemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService/
      - ExceptionManagementDataServiceURL=http://exception-management-data-service:7911/api/ExceptionManagementDataService/
      - GPPracticeDataServiceURL=http://localhost:7999/api/GPPracticeDataService/

  update-exception:
    container_name: update-exception
    image: cohort-manager-update-exception
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ExceptionHandling/UpdateException/Dockerfile
    profiles: [non-essential]
    environment:
      - ASPNETCORE_URLS=http://*:7070
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - ExceptionManagementDataServiceURL=http://exception-management-data-service:7911/api/ExceptionManagementDataService/

  get-validation-exceptions:
    container_name: get-validation-exceptions
    image: cohort-manager-get-validation-exceptions
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/GetValidationExceptions/Dockerfile
    profiles: [ui]
    environment:
      - ASPNETCORE_URLS=http://*:7071
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - DemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService/
      - ExceptionManagementDataServiceURL=http://exception-management-data-service:7911/api/ExceptionManagementDataService/
      - GPPracticeDataServiceURL=http://gppractice-data-service:7999/api/GPPracticeDataService/
      - AcceptableLatencyThresholdMs=500

  # Screening Validation Service
  static-validation:
    container_name: static-validation
    image: cohort-manager-static-validation
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ScreeningValidationService/StaticValidation/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7074
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}

  lookup-validation:
    container_name: lookup-validation
    image: cohort-manager-lookup-validation
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ScreeningValidationService/LookupValidation/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7075
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - BsSelectGpPracticeUrl=http://reference-data-service:7988/api/BsSelectGpPractice
      - BsSelectOutCodeUrl=http://reference-data-service:7988/api/BsSelectOutCode
      - CurrentPostingUrl=http://reference-data-service:7988/api/CurrentPosting
      - ExcludedSMULookupUrl=http://reference-data-service:7988/api/ExcludedSMU
      - BlobContainerName=rules
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True

  # Demographic Services
  retrieve-pds-demographic:
    container_name: retrieve-pds-demographic
    image: cohort-manager-retrieve-pds-demographic
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: DemographicServices/RetrievePDSDemographic/Dockerfile
    profiles: [service-now, nems]
    ports:
      - 8082:8082
    environment:
      - ASPNETCORE_URLS=http://*:8082
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - RetrievePdsParticipantURL=https://sandbox.api.service.nhs.uk/personal-demographics/FHIR/R4/Patient
      - DemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService
      - Kid=RetrievePdsDemographic-DEV1
      - Audience=https://int.api.service.nhs.uk/oauth2/token
      - AuthTokenURL=https://int.api.service.nhs.uk/oauth2/token
      - LocalPrivateKeyFileName=RetrievePdsDemographic-DEV1.pem.key
      - ParticipantManagementTopic=participant-management-topic
      - ServiceBusConnectionString_client_internal=Endpoint=sb://service-bus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - ClientId=Get-private-key-from-NHS-dev-portal
      - UseFakePDSServices=true

  manage-caas-subscription:
      container_name: manage-caas-subscription
      image: cohort-manager-manage-caas-subscription
      networks: [cohman-network]
      profiles: [nems]
      build:
        context: ./src/Functions/
        dockerfile: DemographicServices/ManageCaasSubscription/Dockerfile
      environment:
        - ASPNETCORE_URLS=http://*:9084
        - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
        - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
        - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
        - CaasSubscriptionMeshApiBaseUrl=${MESH_API_BASE_URL:-https://localhost:8700/messageexchange}
        - MeshCaasPassword=password
        - MeshCaasSharedKey=TestKey
        - MeshCaasKeyName=
        - MeshCaasKeyPassword=
        - IsStubbed=false
        - CaasToMailbox=${CAAS_SUBSCRIBE_TO_MAILBOX:-CAAS_TO}
        - CaasFromMailbox=${CAAS_SUBSCRIBE_FROM_MAILBOX:-CAAS_FROM}
        - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      ports:
        - "9084:9084"

  durable-demographic-function:
    container_name: durable-demographic-function
    image: cohort-manager-durable-demographic-function
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: DemographicServices/DemographicDurableFunction/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7079
      - WEBSITE_HOSTNAME=durable-demographic-function:7079
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - DemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - AcceptableLatencyThresholdMs=500
      - MaxRetryCount=3

  # Service Now Integration Service
  servicenow-message-handler:
    container_name: servicenow-message-handler
    image: cohort-manager-servicenow-message-handler
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ServiceNowIntegration/ServiceNowMessageHandler/Dockerfile
    profiles: [service-now]
    environment:
      - ASPNETCORE_URLS=http://*:9092
      - ServiceNowCasesDataServiceURL=http://servicenow-cases-data-service:9996/api/ServiceNowCasesDataService
      - ServiceNowRefreshAccessTokenUrl=http://wiremock:8080/oauth_token.do
      - ServiceNowUpdateUrl=http://wiremock:8080/api/x_nhsd_intstation/nhs_integration/9c78f87c97912e10dd80f2df9153aff5/CohortCaseUpdate
      - ServiceNowResolutionUrl=http://wiremock:8080/api/x_nhsd_intstation/nhs_integration/9c78f87c97912e10dd80f2df9153aff5/CohortCaseResolution
      - ServiceNowGrantType=refresh_token
      - ServiceNowClientId=MockClientId-123
      - ServiceNowClientSecret=MockClientSecret-123
      - ServiceNowRefreshToken=MockRefreshToken-123
      - ServiceNowParticipantManagementTopic=servicenow-participant-management-topic
      - ServiceBusConnectionString_client_internal=Endpoint=sb://service-bus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
    ports:
      - 9092:9092

  # UI
  web:
    container_name: web
    build:
      context: ./src/Web
      dockerfile: Dockerfile
    restart: always
    profiles: [ui]
    ports:
      - "3000:3000"
    networks: [cohman-network]

networks:
  cohman-network:
    external: true
