name: cohort-manager-database

services:
  sql-server:
    container_name: sql-server
    network_mode: host
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${PASSWORD}
    cap_add:
      - SYS_PTRACE
    healthcheck:
      test: [ "CMD-SHELL", "curl -v --silent 127.0.0.1:1433 --stderr - | grep -q 'Empty reply from server'" ]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s

  db-migration:
    container_name: db-migration
    network_mode: host
    build:
      context: ./src/Functions/
      dockerfile: Shared/DataServices.Migrations/Dockerfile
    depends_on:
      - sql-server
    environment:
      - connectionstring=Server=localhost,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
    cap_add:
      - SYS_PTRACE
    restart: "no"
