name: cohort-manager-pipeline
services:
  db-migration:
    container_name: db-migration
    networks: [cohman-network]
    profiles: [pipeline]
    build:
      context: ./src/Functions/
      dockerfile: Shared/DataServices.Migrations/Dockerfile
    environment:
      - DtOsDatabaseConnectionString=Server=sql-server;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
    cap_add:
      - SYS_PTRACE
    restart: "no"

networks:
  cohman-network:
    external: true
