name: cohort-manager

services:
  distribute-participant:
    container_name: distribute-participant
    image: cohort-manager-distribute-participant
    platform: "linux/amd64"
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CohortDistributionServices/DistributeParticipant/Dockerfile
    environment:
      - ServiceBusConnectionString_internal=Endpoint=sb://service-bus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - CohortDistributionTopic=cohort-distribution-topic
      - DistributeParticipantSubscription=distribute-participant-sub
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - WEBSITE_HOSTNAME=distribute-participant:80
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - TransformDataServiceURL=http://transform-data-service:7080/api/TransformDataService
      - ParticipantManagementUrl=http://participant-management-data-service:7994/api/ParticipantManagementDataService
      - CohortDistributionDataServiceUrl=http://cohort-distribution-data-service:7992/api/CohortDistributionDataService/
      - LookupValidationURL=http://lookup-validation:7075/api/LookupValidation
      - StaticValidationURL=http://static-validation:7074/api/StaticValidation
      - ParticipantDemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService
      - RemoveOldValidationRecordUrl=http://remove-validation-exception-data:7085/api/RemoveValidationExceptionData
      - SendServiceNowMessageURL=http://servicenow-message-handler:9092/api/servicenow/send
      - IgnoreParticipantExceptions=false
      - IsExtractedToBSSelect=true
      - MaxLookupValidationRetries=3

  retrieve-cohort-distribution-data:
    container_name: retrieve-cohort-distribution-data
    image: cohort-manager-retrieve-cohort-distribution-data
    platform: "linux/amd64"
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CohortDistributionServices/RetrieveCohortDistribution/Dockerfile
    profiles: [bs-select]
    ports:
      - "7078:7078"
    environment:
      - ASPNETCORE_URLS=http://*:7078
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - CohortDistributionDataServiceURL=http://cohort-distribution-data-service:7992/api/CohortDistributionDataService/
      - BsSelectRequestAuditDataService=http://bs-request-audit-data-service:7956/api/BsSelectRequestAuditDataService/
      - AcceptableLatencyThresholdMs=500

  retrieve-cohort-request-audit:
    container_name: retrieve-cohort-request-audit
    image: cohort-manager-retrieve-cohort-request-audit
    platform: "linux/amd64"
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CohortDistributionServices/RetrieveCohortRequestAudit/Dockerfile
    profiles: [bs-select]
    ports:
      - "7086:7086"
    environment:
      - ASPNETCORE_URLS=http://*:7086
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - CohortDistributionDataServiceURL=http://cohort-distribution-data-service:7992/api/CohortDistributionDataService/
      - BsSelectRequestAuditDataService=http://bs-request-audit-data-service:7956/api/BsSelectRequestAuditDataService/
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException

  transform-data-service:
    container_name: transform-data-service
    image: cohort-manager-transform-data-service
    platform: "linux/amd64"
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CohortDistributionServices/TransformDataService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7080
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - BsSelectOutCodeUrl=http://reference-data-service:7988/api/BsSelectOutCode
      - BsSelectGpPracticeUrl=http://reference-data-service:7988/api/BsSelectGpPractice
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - LanguageCodeUrl=http://reference-data-service:7988/api/LanguageCode
      - ExcludedSMULookupUrl=http://reference-data-service:7988/api/ExcludedSMU
      - AcceptableLatencyThresholdMs=500

  remove-validation-exception-data:
    container_name: remove-validation-exception-data
    image: cohort-manager-remove-validation-exception-data
    platform: "linux/amd64"
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ScreeningValidationService/RemoveValidationException/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7085
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - ExceptionManagementDataServiceURL=http://exception-management-data-service:7911/api/ExceptionManagementDataService
      - DemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService/
      - GPPracticeDataServiceURL=http://gppractice-data-service:7999/api/GPPracticeDataService/
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True


networks:
  cohman-network:
    external: true
