name: cohort-manager

services:
  # CaaS Integration Service
  retrieve-mesh-file:
    container_name: retrieve-mesh-file
    image: cohort-manager-retrieve-mesh-file
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CaasIntegration/RetrieveMeshFile/Dockerfile
    profiles: [non-essential]
    environment:
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - caasfolder_STORAGE=${AZURITE_CONNECTION_STRING}
      - MeshApiBaseUrl=https://localhost:8700/messageexchange
      - BSSMailBox=X26ABC1
      - MeshPassword=${MESHPASSWORD}
      - MeshSharedKey=${MESHSHAREDKEY}
      - MeshKeyName=meshpfx.pfx
      - MeshKeyPassphrase=${MESHKEYPASSPHRASE}
      - ASPNETCORE_URLS=http://*:7059

  nems-mesh-retrieval:
    container_name: nems-mesh-retrieval
    image: cohort-manager-nems-mesh-retrieval
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: NemsSubscriptionService/NemsMeshRetrieval/Dockerfile
    profiles: [nems]
    environment:
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - nemsmeshfolder_STORAGE=${AZURITE_CONNECTION_STRING}
      - NemsMeshApiBaseUrl=https://localhost:8700/messageexchange
      - NemsMeshMailBox=${NEMS_MESH_MAILBOX}
      - NemsMeshPassword=${NEMS_MESH_PASSWORD}
      - NemsMeshSharedKey=${NEMS_MESH_SHARED_KEY}
      - NemsMeshKeyName=nemsmeshpfx.pfx
      - NemsMeshKeyPassphrase=${NEMS_MESH_KEY_PASSPHRASE}
      - NemsMeshBypassServerCertificateValidation=true
      - NemsMeshInboundContainer=nems-updates
      - NemsMeshConfigContainer=nems-config
      - ASPNETCORE_URLS=http://*:7058

  process-nems-update:
    container_name: process-nems-update
    image: cohort-manager-process-nems-update
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: NemsSubscriptionService/ProcessNemsUpdate/Dockerfile
    profiles: [non-essential]
    environment:
      - ASPNETCORE_URLS=http://*:9083
      - caasfolder_STORAGE=${AZURITE_CONNECTION_STRING}
      - NemsMessages="nems-messages"
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - RetrievePdsDemographicURL=http://retrieve-pds-demographic:8082/api/RetrievePDSDemographic
      - UnsubscribeNemsSubscriptionUrl=http://manage-nems-subscription:9081/api/Unsubscribe
      - DemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService
      - ServiceBusConnectionString_client_internal=Endpoint=sb://service-bus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - ParticipantManagementTopic=participant-management-topic

  receive-caas-file:
    container_name: receive-caas-file
    image: cohort-manager-receive-caas-file
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CaasIntegration/receiveCaasFile/Dockerfile
    environment:
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - caasfolder_STORAGE=${AZURITE_CONNECTION_STRING}
      - ASPNETCORE_URLS=http://*:7060
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - DemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService
      - DemographicURI=http://durable-demographic-function:7079/api/DurableDemographicFunction_HttpStart
      - GetOrchestrationStatusURL=http://durable-demographic-function:7079/api/GetOrchestrationStatus
      - AllowDeleteRecords=true
      - BatchSize=3500
      - maxNumberOfChecks=50
      - recordThresholdForBatching=3
      - batchDivisionFactor=5
      - ScreeningLkpDataServiceURL=http://screening-lkp-data-service:8996/api/ScreeningLkpDataService
      - inboundBlobName=inbound
      - ServiceBusConnectionString_client_internal=Endpoint=sb://service-bus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - fileExceptions=file-exceptions
      - ParticipantManagementTopic=participant-management-topic

  # Participant Management Service
  manage-participant:
    container_name: manage-participant
    image: cohort-manager-manage-participant
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ParticipantManagementServices/ManageParticipant/Dockerfile
    environment:
      - ServiceBusConnectionString_internal=Endpoint=sb://service-bus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - ServiceBusConnectionString_client_internal=Endpoint=sb://service-bus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - CohortDistributionTopic=cohort-distribution-topic
      - ParticipantManagementTopic=participant-management-topic
      - ManageParticipantSubscription=manage-participant-sub
      - ParticipantManagementUrl=http://participant-management-data-service:7994/api/ParticipantManagementDataService
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException

  manage-servicenow-participant:
    container_name: manage-servicenow-participant
    image: cohort-manager-manage-servicenow-participant
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ParticipantManagementServices/ManageServiceNowParticipant/Dockerfile
    profiles: [non-essential]
    environment:
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - ServiceNowParticipantManagementTopic=servicenow-participant-management-topic
      - ManageServiceNowParticipantSubscription=manage-servicenow-participant-sub
      - ServiceBusConnectionString_internal=Endpoint=sb://service-bus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - ServiceBusConnectionString_client_internal=Endpoint=sb://service-bus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - RetrievePdsDemographicURL=http://retrieve-pds-demographic:8082/api/RetrievePDSDemographic
      - SendServiceNowMessageURL=http://servicenow-message-handler:9092/api/servicenow/send
      - ParticipantManagementURL=http://participant-management-data-service:7994/api/ParticipantManagementDataService
      - ManageNemsSubscriptionSubscribeURL=http://manage-nems-subscription:9081/api/ManageNemsSubscriptionSubscribeURL
      - CohortDistributionTopic=cohort-distribution-topic

  update-blocked-flag:
    container_name: update-blocked-flag
    image: cohort-manager-update-blocked-flag
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ParticipantManagementServices/UpdateBlockedFlag/Dockerfile
    profiles: [non-essential]
    ports:
      - "7027:7027"
    environment:
      - ASPNETCORE_URLS=http://*:7027
      - AzureWebJobsStorage=UseDevelopmentStorage=true
      - ParticipantManagementUrl=http://participant-management-data-service:7994/api/ParticipantManagementDataService
      - ParticipantDemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService/
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - ManageNemsSubscriptionUnsubscribeURL=http://manage-nems-subscription:9081/api/Unsubscribe
      - ManageNemsSubscriptionSubscribeURL=http://manage-nems-subscription:9081/api/ManageNemsSubscriptionSubscribeURL
      - RetrievePdsDemographicURL=http://etrieve-pds-demographic:8082/api/RetrievePdsDemographic

  delete-participant:
    container_name: delete-participant
    image: cohort-manager-delete-participant
    networks: [cohman-network]
    ports:
    - "7087:7087"
    build:
      context: ./src/Functions/
      dockerfile: ParticipantManagementServices/DeleteParticipant/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7087
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - CohortDistributionDataServiceURL=http://cohort-distribution-data-service:7992/api/CohortDistributionDataService/
      - AcceptableLatencyThresholdMs=500


  # Screening Data Service
  create-exception:
    container_name: create-exception
    image: cohort-manager-create-exception
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ExceptionHandling/CreateException/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7070
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - DemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService/
      - ExceptionManagementDataServiceURL=http://exception-management-data-service:7911/api/ExceptionManagementDataService/
      - GPPracticeDataServiceURL=http://localhost:7999/api/GPPracticeDataService/

  update-exception:
    container_name: update-exception
    image: cohort-manager-update-exception
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ExceptionHandling/UpdateException/Dockerfile
    profiles: [non-essential]
    environment:
      - ASPNETCORE_URLS=http://*:7070
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - ExceptionManagementDataServiceURL=http://exception-management-data-service:7911/api/ExceptionManagementDataService/

  get-validation-exceptions:
    container_name: get-validation-exceptions
    image: cohort-manager-get-validation-exceptions
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/GetValidationExceptions/Dockerfile
    profiles: [ui]
    environment:
      - ASPNETCORE_URLS=http://*:7071
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - DemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService/
      - ExceptionManagementDataServiceURL=http://exception-management-data-service:7911/api/ExceptionManagementDataService/
      - GPPracticeDataServiceURL=http://gppractice-data-service:7999/api/GPPracticeDataService/
      - AcceptableLatencyThresholdMs=500

  # Screening Validation Service
  static-validation:
    container_name: static-validation
    image: cohort-manager-static-validation
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ScreeningValidationService/StaticValidation/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7074
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}

  lookup-validation:
    container_name: lookup-validation
    image: cohort-manager-lookup-validation
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ScreeningValidationService/LookupValidation/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7075
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - BsSelectGpPracticeUrl=http://reference-data-service:7988/api/BsSelectGpPractice
      - BsSelectOutCodeUrl=http://reference-data-service:7988/api/BsSelectOutCode
      - CurrentPostingUrl=http://reference-data-service:7988/api/CurrentPosting
      - ExcludedSMULookupUrl=http://reference-data-service:7988/api/ExcludedSMU
      - BlobContainerName=rules
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True

  # Demographic Services
  retrieve-pds-demographic:
    container_name: retrieve-pds-demographic
    image: cohort-manager-retrieve-pds-demographic
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: DemographicServices/RetrievePDSDemographic/Dockerfile
    profiles: [service-now, nems]
    ports:
      - 8082:8082
    environment:
      - ASPNETCORE_URLS=http://*:8082
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - RetrievePdsParticipantURL=https://sandbox.api.service.nhs.uk/personal-demographics/FHIR/R4/Patient
      - DemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService
      - Kid=RetrievePdsDemographic-DEV1
      - Audience=https://int.api.service.nhs.uk/oauth2/token
      - AuthTokenURL=https://int.api.service.nhs.uk/oauth2/token
      - LocalPrivateKeyFileName=RetrievePdsDemographic-DEV1.pem.key
      - ClientId=Get-private-key-from-NHS-dev-portal
      - UseFakePDSServices=true

  manage-nems-subscription:
      container_name: manage-nems-subscription
      image: cohort-manager-manage-nems-subscription
      networks: [cohman-network]
      profiles: [nems]
      build:
        context: ./src/Functions/
        dockerfile: DemographicServices/ManageNemsSubscription/Dockerfile
      environment:
        - ASPNETCORE_URLS=http://*:9081
        - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
        - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
        - ParticipantDemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService
        - RetrievePdsDemographicURL=http://retrieve-pds-demographic:8082/api/RetrievePDSDemographic
        - NemsFhirEndpoint=https://msg.intspineservices.nhs.uk/STU3
        - NemsFromAsid=200000002527
        - NemsToAsid=200000002527
        - NemsOdsCode=T8T9T
        - NemsMeshMailboxId=${NEMS_MESH_MAILBOX_ID}
        - NemsLocalCertPath=./nhs_signed_client.pfx
        - NemsLocalCertPassword=${NEMS_CERT_PASSWORD}
        - NemsSubscriptionProfile=https://fhir.nhs.uk/STU3/StructureDefinition/EMS-Subscription-1
        - NemsSubscriptionCriteria=https://fhir.nhs.uk/Id/nhs-number
        - NemsDefaultEventTypes0=pds-record-change-1
        - NemsBypassServerCertificateValidation=true
        - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      ports:
        - "9081:9081"

  durable-demographic-function:
    container_name: durable-demographic-function
    image: cohort-manager-durable-demographic-function
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: DemographicServices/DemographicDurableFunction/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7079
      - WEBSITE_HOSTNAME=durable-demographic-function:7079
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - DemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - AcceptableLatencyThresholdMs=500

  # Service Now Integration Service
  servicenow-message-handler:
    container_name: servicenow-message-handler
    image: cohort-manager-servicenow-message-handler
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ServiceNowIntegration/ServiceNowMessageHandler/Dockerfile
    profiles: [service-now]
    environment:
      - ASPNETCORE_URLS=http://*:9092
      - ServiceNowRefreshAccessTokenUrl=https://nhsdigitaldev.service-now.com/oauth_token.do
      - ServiceNowUpdateUrl=https://nhsdigitaldev.service-now.com/api/x_nhsd_intstation/nhs_integration/9c78f87c97912e10dd80f2df9153aff5/CohortCaseUpdate
      - ServiceNowResolutionUrl=https://nhsdigitaldev.service-now.com/api/x_nhsd_intstation/nhs_integration/9c78f87c97912e10dd80f2df9153aff5/CohortCaseResolution
      - ServiceNowClientId=${SERVICENOW_CLIENT_ID}
      - ServiceNowClientSecret=${SERVICENOW_CLIENT_SECRET}
      - ServiceNowRefreshToken=${SERVICENOW_REFRESH_TOKEN}
      - ServiceNowParticipantManagementTopic=servicenow-participant-management-topic
      - ServiceBusConnectionString_client_internal=Endpoint=sb://service-bus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
    ports:
      - 9092:9092

  servicenow-cohort-lookup:
    container_name: servicenow-cohort-lookup
    image: cohort-manager-servicenow-cohort-lookup
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ServiceNowIntegration/ServiceNowCohortLookup/Dockerfile
    profiles: [service-now]
    environment:
      - ASPNETCORE_URLS=http://*:7180
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - ServiceNowCasesDataServiceURL=http://servicenow-cases-data-service:9996/api/ServiceNowCasesDataService
      - CohortDistributionDataServiceURL=http://cohort-distribution-data-service:7992/api/CohortDistributionDataService

  # UI
  web:
    container_name: web
    build:
      context: ./src/Web
      dockerfile: Dockerfile
    restart: always
    profiles: [ui]
    ports:
      - "3000:3000"
    networks: [cohman-network]

networks:
  cohman-network:
    external: true
