name: cohort-manager

services:
  # CaaS Integration Service

  retrieve-mesh-file:
    container_name: retrieve-mesh-file
    image: cohort-manager-retrieve-mesh-file
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CaasIntegration/RetrieveMeshFile/Dockerfile
    profiles: [non-essential]
    environment:
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - caasfolder_STORAGE=${AZURITE_CONNECTION_STRING}
      - MeshApiBaseUrl=https://localhost:8700/messageexchange
      - BSSMailBox=X26ABC1
      - MeshPassword=${MESHPASSWORD}
      - MeshSharedKey=${MESHSHAREDKEY}
      - MeshKeyName=meshpfx.pfx
      - MeshKeyPassphrase=${MESHKEYPASSPHRASE}
      - ASPNETCORE_URLS=http://*:7059

  nems-mesh-retrieval:
    container_name: nems-mesh-retrieval
    image: cohort-manager-nems-mesh-retrieval
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: NemsSubscriptionService/NemsMeshRetrieval/Dockerfile
    profiles: [non-essential]
    environment:
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - nemsmeshfolder_STORAGE=${AZURITE_CONNECTION_STRING}
      - MeshApiBaseUrl=https://localhost:8700/messageexchange
      - BSSMailBox=X26ABC1
      - MeshPassword=${MESHPASSWORD}
      - MeshSharedKey=${MESHSHAREDKEY}
      - MeshKeyName=meshpfx.pfx
      - MeshKeyPassphrase=${MESHKEYPASSPHRASE}
      - ASPNETCORE_URLS=http://*:7058

  receive-caas-file:
    container_name: receive-caas-file
    image: cohort-manager-receive-caas-file
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CaasIntegration/receiveCaasFile/Dockerfile
    environment:
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - caasfolder_STORAGE=${AZURITE_CONNECTION_STRING}
      - ASPNETCORE_URLS=http://*:7060
      - FileValidationURL=http://file-validation:7073/api/FileValidation
      - PMSAddParticipant=http://add-participant:7062/api/addParticipant
      - PMSRemoveParticipant=http://remove-participant:7063/api/RemoveParticipant
      - PMSUpdateParticipant=http://update-participant:7065/api/updateParticipant
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - StaticValidationURL=http://static-validation:7074/api/StaticValidation
      - DemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService
      - DemographicURI=http://durable-demographic-function:7079/api/DurableDemographicFunction_HttpStart
      - GetOrchestrationStatusURL=http://durable-demographic-function:7079/api/GetOrchestrationStatus
      - AllowDeleteRecords=true
      - AddQueueName=add-participant-queue
      - BatchSize=3500
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - recordThresholdForBatching=3
      - batchDivisionFactor=5
      - UpdateQueueName=update-participant-queue
      - ScreeningLkpDataServiceURL=http://screening-lkp-data-service:8996/api/ScreeningLkpDataService

  # Participant Management Service
  add-participant:
    container_name: add-participant
    image: cohort-manager-add-participant
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ParticipantManagementServices/addParticipant/Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./src/Functions/ParticipantManagementServices/addParticipant
    environment:
      - ASPNETCORE_URLS=http://*:7062
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - DSaddParticipant=http://create-participant:7066/api/CreateParticipant
      - DSmarkParticipantAsEligible=http://mark-participant-as-eligible:7067/api/markParticipantAsEligible
      - DemographicURIGet=http://demographic-data-management:7076/api/DemographicDataFunction
      - StaticValidationURL=http://static-validation:7074/api/StaticValidation
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - CohortDistributionServiceURL=http://create-cohort-distribution:7082/api/CreateCohortDistribution
      - CohortQueueName=cohort-distribution-queue
      - AddQueueName=add-participant-queue

  remove-participant:
    container_name: remove-participant
    image: cohort-manager-remove-participant
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ParticipantManagementServices/RemoveParticipant/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7063
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - markParticipantAsIneligible=http://mark-participant-as-ineligible:7068/api/markParticipantAsIneligible
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - DemographicURIGet=http://demographic-data-management:7076/api/DemographicDataFunction
      - RemoveCohortDistributionURL=http://durable-demographic-function:7079/api/RemoveCohortDistributionData
      - CohortQueueName=cohort-distribution-queue

  update-participant:
    container_name: update-participant
    image: cohort-manager-update-participant
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ParticipantManagementServices/updateParticipant/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7065
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - UpdateParticipant=http://update-participant-details:7069/api/updateParticipantDetails
      - StaticValidationURL=http://static-validation:7074/api/StaticValidation
      - DemographicURIGet=http://demographic-data-management:7076/api/DemographicDataFunction
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - DSmarkParticipantAsEligible=http://mark-participant-as-eligible:7067/api/markParticipantAsEligible
      - markParticipantAsIneligible=http://mark-participant-as-ineligible:7068/api/markParticipantAsIneligible
      - CohortDistributionServiceURL=http://create-cohort-distribution:7082/api/CreateCohortDistribution
      - CohortQueueName=cohort-distribution-queue
      - UpdateQueueName=update-participant-queue

  update-participant-from-screening-provider:
    container_name: update-participant-from-screening-provider
    image: cohort-manager-update-participant-from-screening-provider
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ParticipantManagementServices/UpdateParticipantFromScreeningProvider/Dockerfile
    profiles: [bi-analytics]
    environment:
      - ASPNETCORE_URLS=http://*:8001
      - ParticipantManagementUrl=http://participant-management-data-service:7994/api/ParticipantManagementDataService
      - GeneCodeLkpUrl=http://gene-code-lkp-data-service:7991/api/GeneCodeLkpDataService
      - HigherRiskReferralReasonLkpUrl=http://higher-risk-referral-reason-lkp-data-service:7992/api/HigherRiskReferralReasonLkpDataService
      - topicEndpoint=${EVENTGRID_URL}
      - topicKey=${EVENTGRID_KEY}
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException

  check-participant-exists:
    container_name: check-participant-exists
    image: cohort-manager-check-participant-exists
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ParticipantManagementServices/CheckParticipantExists/Dockerfile
    profiles: [bi-analytics]
    environment:
      - ASPNETCORE_URLS=http://*:8002
      - ParticipantManagementUrl=http://participant-management-data-service:7994/api/ParticipantManagementDataService

  get-participant-reference-data:
    container_name: get-participant-reference-data
    image: cohort-manager-get-participant-reference-data
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ParticipantManagementServices/GetParticipantReferenceData/Dockerfile
    profiles: [bi-analytics]
    environment:
      - ASPNETCORE_URLS=http://*:7999
      - HigherRiskReferralReasonLkpDataServiceUrl=http://higher-risk-referral-reason-lkp-data-service:7992/api/HigherRiskReferralReasonLkpDataService
      - GeneCodeLkpDataServiceUrl=http://gene-code-lkp-data-service:7991/api/GeneCodeLkpDataService

  # Screening Data Service
  create-participant:
    container_name: create-participant
    image: cohort-manager-create-participant
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/createParticipant/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7066
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - LookupValidationURL=http://lookup-validation:7075/api/LookupValidation
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - ParticipantManagementUrl=http://participant-management-data-service:7994/api/ParticipantManagementDataService
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - AcceptableLatencyThresholdMs=500

  mark-participant-as-eligible:
    container_name: mark-participant-as-eligible
    image: cohort-manager-mark-participant-as-eligible
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/markParticipantAsEligible/Dockerfile
    environment:
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - ASPNETCORE_URLS=http://*:7067
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - LookupValidationURL=http://lookup-validation:7075/api/LookupValidation
      - StaticValidationURL=http://static-validation:7074/api/StaticValidation
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - ParticipantManagementUrl=http://participant-management-data-service:7994/api/ParticipantManagementDataService
      - AcceptableLatencyThresholdMs=500

  mark-participant-as-ineligible:
    container_name: mark-participant-as-ineligible
    image: cohort-manager-mark-participant-as-ineligible
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/markParticipantAsIneligible/Dockerfile
    environment:
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - ASPNETCORE_URLS=http://*:7068
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - LookupValidationURL=http://lookup-validation:7075/api/LookupValidation
      - StaticValidationURL=http://static-validation:7074/api/StaticValidation
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - ParticipantManagementUrl=http://participant-management-data-service:7994/api/ParticipantManagementDataService
      - AcceptableLatencyThresholdMs=500

  update-participant-details:
    container_name: update-participant-details
    image: cohort-manager-update-participant-details
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/updateParticipantDetails/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7069
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - LookupValidationURL=http://lookup-validation:7075/api/LookupValidation
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - ParticipantManagementUrl=http://participant-management-data-service:7994/api/ParticipantManagementDataService
      - AcceptableLatencyThresholdMs=500

  create-exception:
    container_name: create-exception
    image: cohort-manager-create-exception
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ExceptionHandling/CreateException/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7070
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - DemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService/
      - ExceptionManagementDataServiceURL=http://exception-management-data-service:7911/api/ExceptionManagementDataService/
      - GPPracticeDataServiceURL=http://localhost:7999/api/GPPracticeDataService/

  get-validation-exceptions:
    container_name: get-validation-exceptions
    image: cohort-manager-get-validation-exceptions
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/GetValidationExceptions/Dockerfile
    profiles: [ui]
    environment:
      - ASPNETCORE_URLS=http://*:7071
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - DemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService/
      - ExceptionManagementDataServiceURL=http://exception-management-data-service:7911/api/ExceptionManagementDataService/
      - GPPracticeDataServiceURL=http://gppractice-data-service:7999/api/GPPracticeDataService/
      - AcceptableLatencyThresholdMs=500

  # Screening Validation Service
  file-validation:
    container_name: file-validation
    image: cohort-manager-file-validation
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ScreeningValidationService/FileValidation/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7073
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - inboundBlobName=inbound
      - caasfolder_STORAGE=${AZURITE_CONNECTION_STRING}
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - fileExceptions=file-exceptions

  static-validation:
    container_name: static-validation
    image: cohort-manager-static-validation
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ScreeningValidationService/StaticValidation/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7074
      - CreateValidationExceptionURL=http://create-exception:7070/api/CreateValidationException
      - BlobContainerName=rules
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - RemoveOldValidationRecord=http://remove-validation-exception-data:7085/api/RemoveValidationExceptionData

  lookup-validation:
    container_name: lookup-validation
    image: cohort-manager-lookup-validation
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ScreeningValidationService/LookupValidation/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7075
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - BsSelectGpPracticeUrl=http://bs-select-gp-practice-data-service:7998/api/BsSelectGpPracticeDataService
      - BsSelectOutCodeUrl=http://bs-select-outcode-data-service:7881/api/BsSelectOutCodeDataService
      - LanguageCodeUrl=http://language-code-data-service:7997/api/LanguageCodeDataService
      - CurrentPostingUrl=http://current-posting-data-service:7996/api/CurrentPostingDataService
      - ExcludedSMULookupUrl=http://excluded-smu-data-service:7995/api/ExcludedSMUDataService
      - BlobContainerName=rules
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True

  # Demographic Services
  demographic-data-management:
    container_name: demographic-data-management
    image: cohort-manager-demographic-data-management
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: DemographicServices/DemographicDataManagementFunction/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7076
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - ParticipantDemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService

  retrieve-pds-demographic:
    container_name: retrieve-pds-demographic
    image: cohort-manager-retrieve-pds-demographic
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: DemographicServices/RetrievePDSDemographic/Dockerfile
    profiles: [not-implemented]
    environment:
      - ASPNETCORE_URLS=http://*:8082
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - RetrievePdsParticipantURL=https://sandbox.api.service.nhs.uk/personal-demographics/FHIR/R4/Patient

  nems-subscribe:
    container_name: nems-subscribe
    image: cohort-manager-nems-subscribe
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: DemographicServices/NEMSSubscribe/Dockerfile
    profiles: [not-implemented]
    environment:
      - ASPNETCORE_URLS=http://*:9081
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - ParticipantDemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService
      - RetrievePdsDemographicURL=http://retrieve-pds-demographic:8082/api/RetrievePDSDemographic

  nems-unsubscribe:
    container_name: nems-unsubscribe
    image: cohort-manager-nems-unsubscribe
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: DemographicServices/NEMSUnSubscription/Dockerfile
    profiles: [not-implemented]
    environment:
      - ASPNETCORE_URLS=http://*:9082
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - ParticipantDemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService
  durable-demographic-function:
    container_name: durable-demographic-function
    image: cohort-manager-durable-demographic-function
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: DemographicServices/DemographicDurableFunction/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7079
      - WEBSITE_HOSTNAME=localhost:7079
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - DemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - AcceptableLatencyThresholdMs=500

    # UI
  web:
    container_name: web
    build:
      context: ./src/Web
      dockerfile: Dockerfile
    restart: always
    profiles: [ui]
    ports:
      - "3000:3000"
    networks: [cohman-network]

networks:
  cohman-network:
    external: true
