name: cohort-manager

services:
  add-cohort-distribution-data:
    container_name: add-cohort-distribution-data
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CohortDistributionServices/AddCohortDistributionData/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7077
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - CohortDistributionDataServiceURL=http://cohort-distribution-data-service:7992/api/CohortDistributionDataService/

  retrieve-cohort-distribution-data:
    container_name: retrieve-cohort-distribution-data
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CohortDistributionServices/RetrieveCohortDistribution/Dockerfile
    profiles: [non-essential]
    environment:
      - ASPNETCORE_URLS=http://*:7078
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException

  retrieve-cohort-request-audit:
    container_name: retrieve-cohort-request-audit
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CohortDistributionServices/RetrieveCohortRequestAudit/Dockerfile
    profiles: [non-essential]
    environment:
      - ASPNETCORE_URLS=http://*:7086
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException

  transform-data-service:
    container_name: transform-data-service
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CohortDistributionServices/TransformDataService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7080
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - BsSelectOutCodeUrl=http://bs-select-outcode-data-service:7881/api/BsSelectOutCodeDataService
      - BsSelectGpPracticeUrl=http://bs-select-gp-practice-data-service:7998/api/BsSelectGpPracticeDataService/
      - CohortDistributionDataServiceUrl=http://cohort-distribution-data-service:7992/api/CohortDistributionDataService/
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True

  allocate-service-provider:
    container_name: allocate-service-provider
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CohortDistributionServices/ServiceProviderAllocationService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7081
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException

  create-cohort-distribution:
    container_name: create-cohort-distribution
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CohortDistributionServices/CreateCohortDistribution/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7082
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - AllocateScreeningProviderURL=http://allocate-service-provider:7081/api/AllocateServiceProviderToParticipantByService
      - TransformDataServiceURL=http://transform-data-service:7080/api/TransformDataService
      - RetrieveParticipantDataURL=http://retrieve-participant-data:7083/api/RetrieveParticipantData
      - AddCohortDistributionURL=http://add-cohort-distribution-data:7077/api/AddCohortDistributionData
      - ValidateCohortDistributionRecordURL=http://validate-cohort-distribution-record:7084/api/ValidateCohortDistributionRecord
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - CohortQueueName=cohort-distribution-queue
      - CohortQueueNamePoison=cohort-distribution-queue-poison
      - IgnoreParticipantExceptions=false
      - IsExtractedToBSSelect=true

  retrieve-participant-data:
    container_name: retrieve-participant-data
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CohortDistributionServices/RetrieveParticipantData/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7083
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - ParticipantManagementUrl=http://participant-management-data-service:7994/api/ParticipantManagementDataService
      - DemographicDataFunctionURL=http://demographic-data-management:7076/api/DemographicDataFunction

  validate-cohort-distribution-record:
    container_name: validate-cohort-distribution-record
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CohortDistributionServices/ValidateCohortDistributionRecord/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7084
      - LookupValidationURL=http://lookup-validation:7075/api/LookupValidation
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
      - CohortDistributionDataServiceURL=http://cohort-distribution-data-service:7992/api/CohortDistributionDataService/

  remove-validation-exception-data:
    container_name: remove-validation-exception-data
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ScreeningValidationService/RemoveValidationException/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7085
      - ExceptionFunctionURL=http://create-exception:7070/api/CreateException
      - ExceptionManagementDataServiceURL=http://exception-management-data-service:7911/api/ExceptionManagementDataService
      - DemographicDataServiceURL=http://participant-demographic-data-service:7993/api/ParticipantDemographicDataService/
      - GPPracticeDataServiceURL=http://gppractice-data-service:7999/api/GPPracticeDataService/
      - DtOsDatabaseConnectionString=Server=db,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True