name: cohort-manager-deps

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    networks: [cohman-network]
    command: azurite --silent --skipApiVersionCheck --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  azurite-setup:
    container_name: azurite-setup
    build:
      context: ./
      dockerfile: ./Set-up/azurite/Dockerfile
    networks: [cohman-network]
    depends_on:
      - azurite
    environment:
      - AZURITE_CONNECTION_STRING=${AZURITE_CONNECTION_STRING}

  sql-server:
    container_name: sql-server
    networks: [cohman-network]
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${PASSWORD}
    cap_add:
      - SYS_PTRACE
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD-SHELL", "curl -v --silent 127.0.0.1:1433 --stderr - | grep -q 'Empty reply from server'" ]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s

  db-migration:
    container_name: db-migration
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: Shared/DataServices.Migrations/Dockerfile
    depends_on:
      - sql-server
    environment:
      - DtOsDatabaseConnectionString=Server=sql-server;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True
    cap_add:
      - SYS_PTRACE
    restart: "no"

networks:
  cohman-network:
    name: cohman-network
    driver: bridge
