name: cohort-manager-web

services:
  web:
    container_name: "web"
    build:
      context: ./src/web
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks: [cohman-network]
