IF NOT EXISTS
(
    SELECT *
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
          AND TABLE_NAME = 'CAAS_PARTICIPANT'
)
BEGIN
    CREATE TABLE [dbo].[CAAS_PARTICIPANT] 
    (
        [RECORD_TYPE] VARCHAR (10) NULL,
        [CHANGE_TIME_STAMP] NUMERIC (20) NULL,
        [SERIAL_CHANGE_NUMBER] INT NULL,
        [NHS_NUMBER] VARCHAR (10) NOT NULL,
        [SUPERSEDED_BY_NHS_NUMBER] VARCHAR (10) NULL,
        [PRIMARY_CARE_PROVIDER] VARCHAR (10) NULL,  
        [PRIMARY_CARE_PROVIDER_BUSINESS_EFFECTIVE_FROM_DATE] DATE NULL,
        [CURRENT_POSTING] VARCHAR (3) NULL,
        [CURRENT_POSTING_BUSINESS_EFFECTIVE_FROM_DATE] DATE NULL,
        [NAME_PREFIX] VARCHAR (35) NULL,
        [GIVEN_NAME] VARCHAR (35) NULL,
        [OTHER_GIVEN_NAME(S)] VARCHAR (100) NULL,
        [FAMILY_NAME] VARCHAR (35) NULL,
        [PREVIOUS_FAMILY_NAME] VARCHAR (35) NULL,
        [DATE_OF_BIRTH] DATE NOT NULL,
        [GENDER] TINYINT NULL,
        [ADDRESS_LINE_1] VARCHAR (35) NULL,
        [ADDRESS_LINE_2] VARCHAR (35) NULL,
        [ADDRESS_LINE_3] VARCHAR (35) NULL,
        [ADDRESS_LINE_4] VARCHAR (35) NULL,
        [ADDRESS_LINE_5] VARCHAR (35) NULL,
        [POSTCODE] VARCHAR (8) NULL,
        [PAF_KEY] VARCHAR (8) NULL,
        [USUAL_ADDRESS_BUSINESS_EFFECTIVE_FROM_DATE] DATE NULL,
        [REASON_FOR_REMOVAL] VARCHAR (3) NULL,
        [REASON_FOR_REMOVAL_BUSINESS_EFFECTIVE_FROM_DATE] DATE NULL,
        [DATE_OF_DEATH] DATE NULL,
        [DEATH_STATUS] TINYINT NULL,
        [TELEPHONE_NUMBER(HOME)] VARCHAR (32) NULL,
        [TELEPHONE_NUMBER(HOME)_BUSINESS_EFFECTIVE_FROM_DATE] DATE NULL,
        [TELEPHONE_NUMBER(MOBILE)] VARCHAR (32) NULL,
        [TELEPHONE_NUMBER(MOBILE)_BUSINESS_EFFECTIVE_FROM_DATE] DATE NULL,
        [E-MAIL_ADDRESS(HOME)] NVARCHAR (90) NULL,
        [E-MAIL_ADDRESS(HOME)_BUSINESS_EFFECTIVE_FROM_DATE] DATE NULL,
        [PREFERRED_LANGUAGE] VARCHAR (2) NULL,
        [INTERPRETER_REQUIRED] BIT NULL,
        [INVALID_FLAG] BIT NULL,
        [ELIGIBILITY] BIT NULL,
        PRIMARY KEY (NHS_NUMBER, DATE_OF_BIRTH)
    );
END

IF NOT EXISTS
(
    SELECT *
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
          AND TABLE_NAME = 'BSS_PARTICIPANT'
)
BEGIN
    CREATE TABLE [dbo].[BSS_PARTICIPANT]
    (
        NHS_NUMBER VARCHAR(10) NOT NULL,
        DATE_OF_BIRTH DATE NOT NULL,
        PRIMARY_CARE_PROVIDER VARCHAR(8),                   
        REASON_FOR_REMOVAL VARCHAR(100),
        REASON_FOR_REMOVAL_BUSINESS_EFFECTIVE_FROM_DATE DATE, 
        DATE_OF_DEATH DATE,
        POSTCODE VARCHAR(8),                                  
        GENDER VARCHAR(20),
        IS_HIGHER_RISK TINYINT NOT NULL,
        PRIMARY KEY (NHS_NUMBER, DATE_OF_BIRTH)
    );
END
