CREATE TABLE [dbo].[BS_COHORT_DISTRIBUTION] (
    [BS_COHORT_DISTRIBUTION_ID]     INT              IDENTITY (1, 1) NOT NULL,
    [PARTICIPANT_ID]                BIGINT           NULL,
    [NHS_NUMBER]                    BIGINT           NULL,
    [SUPERSEDED_NHS_NUMBER]         BIGINT           NULL,
    [PRIMARY_CARE_PROVIDER_FROM_DT] DATE             NULL,
    [NAME_PREFIX]                   VARCHAR (10)     NULL,
    [GIVEN_NAME]                    VARCHAR (100)    NULL,
    [OTHER_GIVEN_NAME]              int    NULL,
    [FAMILY_NAME]                   VARCHAR (100)    NULL,
    [PREVIOUS_FAMILY_NAME]          VARCHAR (100)    NULL,
    [DATE_OF_BIRTH]                 DATE             NULL,
    [GENDER]                        SMALLINT         NULL,
    [ADDRESS_LINE_1]                VARCHAR (100)    NULL,
    [ADDRESS_LINE_2]                VARCHAR (100)    NULL,
    [ADDRESS_LINE_3]                VARCHAR (100)    NULL,
    [ADDRESS_LINE_4]                VARCHAR (100)    NULL,
    [ADDRESS_LINE_5]                VARCHAR (100)    NULL,
    [POST_CODE]                     VARCHAR (10)     NULL,
    [USUAL_ADDRESS_FROM_DT]         DATE             NULL,
    [CURRENT_POSTING]               VARCHAR (10)     NULL,
    [CURRENT_POSTING_FROM_DT]       DATE             NULL,
    [DATE_OF_DEATH]                 DATE             NULL,
    [TELEPHONE_NUMBER_HOME]         VARCHAR (35)     NULL,
    [TELEPHONE_NUMBER_HOME_FROM_DT] DATE             NULL,
    [TELEPHONE_NUMBER_MOB]          VARCHAR (35)     NULL,
    [TELEPHONE_NUMBER_MOB_FROM_DT]  DATE             NULL,
    [EMAIL_ADDRESS_HOME]            VARCHAR (100)    NULL,
    [EMAIL_ADDRESS_HOME_FROM_DT]    DATE             NULL,
    [PREFERRED_LANGUAGE]            VARCHAR (35)     NULL,
    [INTERPRETER_REQUIRED]          SMALLINT         NULL,
    [REASON_FOR_REMOVAL]            VARCHAR (10)     NULL,
    [REASON_FOR_REMOVAL_FROM_DT]    DATE             NULL,
    [IS_EXTRACTED]                  SMALLINT         NULL,
    [RECORD_INSERT_DATETIME]        DATE             NULL,
    [RECORD_UPDATE_DATETIME]        DATE             NULL,
    [REQUEST_ID]                    UNIQUEIDENTIFIER NULL,
    CONSTRAINT [BS_COHORT_DISTRIBUTION_PK] PRIMARY KEY CLUSTERED ([BS_COHORT_DISTRIBUTION_ID] ASC)
);


GO

