CREATE TABLE [dbo].[CURRENT_POSTING_LKP] (
    [POSTING]            VARCHAR (4)  NOT NULL,
    [IN_USE]             VARCHAR (1)  NULL,
    [INCLUDED_IN_COHORT] VARCHAR (1)  NULL,
    [POSTING_CATEGORY]   VARCHAR (10) NULL,
    PRIMARY KEY CLUSTERED ([POSTING] ASC)
);


GO

