CREATE TABLE [dbo].[PARTICIPANT_MANAGEMENT] (
    [PARTICIPANT_ID]             BIGINT       IDENTITY (1, 1) NOT NULL,
    [SCREENING_ID]               BIGINT       NULL,
    [NHS_NUMBER]                 BIGINT       NULL,
    [RECORD_TYPE]                VARCHAR (10) NULL,
    [REASON_FOR_REMOVAL]         VARCHAR (10) NULL,
    [REASON_FOR_REMOVAL_FROM_DT] DATE         NULL,
    [BUSINESS_RULE_VERSION]      VARCHAR (10) NULL,
    [EXCEPTION_FLAG]             SMALLINT     NULL,
    [RECORD_INSERT_DATETIME]     DATETIME     NULL,
    [RECORD_UPDATE_DATETIME]     DATETIME     NULL,
    CONSTRAINT [PK_PARTICIPANT_MANAGEMENT] PRIMARY KEY CLUSTERED ([PARTICIPANT_ID] ASC),
    CONSTRAINT [FK_PARTICIP_SCREENING_SCREENIN] FOREIGN KEY ([SCREENING_ID]) REFERENCES [dbo].[SCREENING_LKP] ([SCREENING_ID])
);


GO

