CREATE TABLE [dbo].[SCREENING_LKP] (
    [SCREENING_ID]      BIGINT       IDENTITY (1, 1) NOT NULL,
    [SCREENING_NAME]    VARCHAR (50) NULL,
    [SCREENING_TYPE]    VARCHAR (50) NULL,
    [SCREENING_ACRONYM] VARCHAR (50) NULL,
    CONSTRAINT [PK_SCREENING_LKP] PRIMARY KEY CLUSTERED ([SCREENING_ID] ASC)
);


GO

