name: UI Tests

on:
  pull_request:
    paths:
      - "application/CohortManager/src/Web/**"
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: application/CohortManager/src/Web

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true
          cache: "npm"
          cache-dependency-path: application/CohortManager/src/Web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Unit tests
        run: npm run test:unit

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        env:
          SERVICE_NAME: ${{ vars.SERVICE_NAME }}
          APP_ENV: ${{ vars.APP_ENV }}
          NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
          EXCEPTIONS_API_URL: ${{ vars.EXCEPTIONS_API_URL }}
          COHORT_MANAGER_RBAC_CODE: ${{ vars.COHORT_MANAGER_USERS }}
        run: npm run test:e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: application/CohortManager/src/Web/test-results/
          retention-days: 30
