name: "Manual Cohort Manager Image Build"

on:
  workflow_dispatch:
    inputs:
      environment_tag:
        description: Environment of the deployment
        required: true
        type: string
        default: development
      build_all_images:
        description: Build all images defined in compose files
        required: false
        type: boolean
        default: false

jobs:
  manual-build-and-push-images:
    name: Manual Build and Push all images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: read

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: 'main' # We ensure it's the main branch.

      - name: "Call Reusable Build Images Workflow"
        uses: NHSDigital/dtos-devops-templates/.github/workflows/stage-3-build-images.yaml@main
        with:
          docker_compose_file: application/CohortManager/compose.yaml
          excluded_containers_csv_list: azurite,azurite-setup,sql-edge,db-setup
          environment_tag: ${{ needs.metadata.outputs.environment_tag }}
          function_app_source_code_path: application/CohortManager/src
          project_name: cohort-manager
          build_all_services: ${{ github.event.inputs.build_all_services }}
        secrets: inherit
