name: "Manual Cohort Manager Image Build"

on:
  workflow_dispatch:
    inputs:
      environment_tag:
        description: Select the environment for the deployment
        required: true
        type: choice
        default: development
        options:
          - development
          - nft
          - integration

jobs:
  manual-build-and-push-images:
    name: Manual Build and Push all images
    uses: NHSDigital/dtos-devops-templates/.github/workflows/stage-3-build-images.yaml@main
    secrets:
      client_id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      acr_name: ${{ secrets.ACR_NAME }}
    with:
      docker_compose_file: application/CohortManager/compose.yaml
      excluded_containers_csv_list: azurite,azurite-setup,sql-server
      environment_tag: ${{ github.event.inputs.environment_tag }}
      function_app_source_code_path: application/CohortManager/src
      project_name: cohort-manager
      build_all_images: true
