name: Docker Image CI

on:
  push:
    branches: ["DTOSS-3494-dokcer-build-changed-functions"]

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - uses: tj-actions/changed-files@v44 
        id: changed-files
        # with:
          # dir_names: "true"

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done


    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
