name: Docker Image CI

on:
  push:
    branches: ["DTOSS-3494-dokcer-build-changed-functions"]

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    name: Get a list of changed functions
    uses: tj-actions/changed-files@v44 
    with:
      dir_names: "true"
    run: |
      for dir in ${{ steps.changed_files.outputs.all_changed_directories }}; do
        echo "$dir"
      done


    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
