name: Docker Image CI

on:
  push:
    branches: ["DTOSS-3494-dokcer-build-changed-functions"]

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - uses: tj-actions/changed-files@v44 
        id: changed-files
        with:
          path: application/CohortManager/src/Functions
          dir_names: "true"

      - name: get docker compose function name(s)
        id: get-function-names
        env:
          CHANGED_FOLDERS: ${{steps.changed-files.outputs.all_changed_files}}
        run: |
          bash ./scripts/deployment/get-docker-names.sh

      - name: print function names
        run: echo "${{steps.get-function-names.outputs.FUNC_NAMES}}"

      - name: build docker images
        working-directory: ./application/CohortManager
        run: |
          if [ -z "$steps.get-function-names.outputs.FUNC_NAMES" ]; then
            echo "No functions changed"
          else
            docker compose build${{steps.get-function-names.outputs.FUNC_NAMES}}
          fi
    
