name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore application/CohortManager/src/Functions/Functions.sln

      - name: Build solution
        run: dotnet build --no-restore --configuration Release
        working-directory: application/CohortManager/src/Functions

      - name: Run tests with coverage
        run: |
          mkdir -p TestResults
          dotnet test application/CohortManager/src/Tests/TestUtils/TestUtils.csproj \
            --collect:"XPlat Code Coverage" \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=nhsdigital
            -Dsonar.projectKey=dtos-cohort-manager
            -Dsonar.cs.opencover.reportsPaths=TestResults/coverage.opencover.xml
